// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/file"
	"github.com/ppxb/miyabi/internal/ent/movie"
)

// FileCreate is the builder for creating a File entity.
type FileCreate struct {
	config
	mutation *FileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *FileCreate) SetCreatedAt(v time.Time) *FileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FileCreate) SetNillableCreatedAt(v *time.Time) *FileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FileCreate) SetUpdatedAt(v time.Time) *FileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FileCreate) SetNillableUpdatedAt(v *time.Time) *FileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFileID sets the "file_id" field.
func (_c *FileCreate) SetFileID(v string) *FileCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetPickCode sets the "pick_code" field.
func (_c *FileCreate) SetPickCode(v string) *FileCreate {
	_c.mutation.SetPickCode(v)
	return _c
}

// SetNillablePickCode sets the "pick_code" field if the given value is not nil.
func (_c *FileCreate) SetNillablePickCode(v *string) *FileCreate {
	if v != nil {
		_c.SetPickCode(*v)
	}
	return _c
}

// SetSha1 sets the "sha1" field.
func (_c *FileCreate) SetSha1(v string) *FileCreate {
	_c.mutation.SetSha1(v)
	return _c
}

// SetNillableSha1 sets the "sha1" field if the given value is not nil.
func (_c *FileCreate) SetNillableSha1(v *string) *FileCreate {
	if v != nil {
		_c.SetSha1(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *FileCreate) SetName(v string) *FileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *FileCreate) SetSize(v int64) *FileCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *FileCreate) SetParentID(v string) *FileCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *FileCreate) SetNillableParentID(v *string) *FileCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *FileCreate) SetAccountID(v string) *FileCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *FileCreate) SetNillableAccountID(v *string) *FileCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetRootID sets the "root_id" field.
func (_c *FileCreate) SetRootID(v string) *FileCreate {
	_c.mutation.SetRootID(v)
	return _c
}

// SetNillableRootID sets the "root_id" field if the given value is not nil.
func (_c *FileCreate) SetNillableRootID(v *string) *FileCreate {
	if v != nil {
		_c.SetRootID(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *FileCreate) SetPath(v string) *FileCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *FileCreate) SetNillablePath(v *string) *FileCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetScanID sets the "scan_id" field.
func (_c *FileCreate) SetScanID(v string) *FileCreate {
	_c.mutation.SetScanID(v)
	return _c
}

// SetNillableScanID sets the "scan_id" field if the given value is not nil.
func (_c *FileCreate) SetNillableScanID(v *string) *FileCreate {
	if v != nil {
		_c.SetScanID(*v)
	}
	return _c
}

// SetMovieID sets the "movie_id" field.
func (_c *FileCreate) SetMovieID(v int) *FileCreate {
	_c.mutation.SetMovieID(v)
	return _c
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_c *FileCreate) SetNillableMovieID(v *int) *FileCreate {
	if v != nil {
		_c.SetMovieID(*v)
	}
	return _c
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_c *FileCreate) SetMovie(v *Movie) *FileCreate {
	return _c.SetMovieID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_c *FileCreate) Mutation() *FileMutation {
	return _c.mutation
}

// Save creates the File in the database.
func (_c *FileCreate) Save(ctx context.Context) (*File, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileCreate) SaveX(ctx context.Context) *File {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := file.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := file.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PickCode(); !ok {
		v := file.DefaultPickCode
		_c.mutation.SetPickCode(v)
	}
	if _, ok := _c.mutation.Sha1(); !ok {
		v := file.DefaultSha1
		_c.mutation.SetSha1(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := file.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		v := file.DefaultAccountID
		_c.mutation.SetAccountID(v)
	}
	if _, ok := _c.mutation.RootID(); !ok {
		v := file.DefaultRootID
		_c.mutation.SetRootID(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := file.DefaultPath
		_c.mutation.SetPath(v)
	}
	if _, ok := _c.mutation.ScanID(); !ok {
		v := file.DefaultScanID
		_c.mutation.SetScanID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "File.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "File.updated_at"`)}
	}
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "File.file_id"`)}
	}
	if v, ok := _c.mutation.FileID(); ok {
		if err := file.FileIDValidator(v); err != nil {
			return &ValidationError{Name: "file_id", err: fmt.Errorf(`ent: validator failed for field "File.file_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PickCode(); !ok {
		return &ValidationError{Name: "pick_code", err: errors.New(`ent: missing required field "File.pick_code"`)}
	}
	if _, ok := _c.mutation.Sha1(); !ok {
		return &ValidationError{Name: "sha1", err: errors.New(`ent: missing required field "File.sha1"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "File.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := file.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "File.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "File.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := file.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "File.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "File.parent_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "File.account_id"`)}
	}
	if _, ok := _c.mutation.RootID(); !ok {
		return &ValidationError{Name: "root_id", err: errors.New(`ent: missing required field "File.root_id"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "File.path"`)}
	}
	if _, ok := _c.mutation.ScanID(); !ok {
		return &ValidationError{Name: "scan_id", err: errors.New(`ent: missing required field "File.scan_id"`)}
	}
	return nil
}

func (_c *FileCreate) sqlSave(ctx context.Context) (*File, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileCreate) createSpec() (*File, *sqlgraph.CreateSpec) {
	var (
		_node = &File{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(file.Table, sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(file.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(file.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FileID(); ok {
		_spec.SetField(file.FieldFileID, field.TypeString, value)
		_node.FileID = value
	}
	if value, ok := _c.mutation.PickCode(); ok {
		_spec.SetField(file.FieldPickCode, field.TypeString, value)
		_node.PickCode = value
	}
	if value, ok := _c.mutation.Sha1(); ok {
		_spec.SetField(file.FieldSha1, field.TypeString, value)
		_node.Sha1 = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(file.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(file.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(file.FieldParentID, field.TypeString, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(file.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.RootID(); ok {
		_spec.SetField(file.FieldRootID, field.TypeString, value)
		_node.RootID = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(file.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.ScanID(); ok {
		_spec.SetField(file.FieldScanID, field.TypeString, value)
		_node.ScanID = value
	}
	if nodes := _c.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.MovieTable,
			Columns: []string{file.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MovieID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.File.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FileCreate) OnConflict(opts ...sql.ConflictOption) *FileUpsertOne {
	_c.conflict = opts
	return &FileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.File.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FileCreate) OnConflictColumns(columns ...string) *FileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FileUpsertOne{
		create: _c,
	}
}

type (
	// FileUpsertOne is the builder for "upsert"-ing
	//  one File node.
	FileUpsertOne struct {
		create *FileCreate
	}

	// FileUpsert is the "OnConflict" setter.
	FileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *FileUpsert) SetUpdatedAt(v time.Time) *FileUpsert {
	u.Set(file.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileUpsert) UpdateUpdatedAt() *FileUpsert {
	u.SetExcluded(file.FieldUpdatedAt)
	return u
}

// SetFileID sets the "file_id" field.
func (u *FileUpsert) SetFileID(v string) *FileUpsert {
	u.Set(file.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FileUpsert) UpdateFileID() *FileUpsert {
	u.SetExcluded(file.FieldFileID)
	return u
}

// SetPickCode sets the "pick_code" field.
func (u *FileUpsert) SetPickCode(v string) *FileUpsert {
	u.Set(file.FieldPickCode, v)
	return u
}

// UpdatePickCode sets the "pick_code" field to the value that was provided on create.
func (u *FileUpsert) UpdatePickCode() *FileUpsert {
	u.SetExcluded(file.FieldPickCode)
	return u
}

// SetSha1 sets the "sha1" field.
func (u *FileUpsert) SetSha1(v string) *FileUpsert {
	u.Set(file.FieldSha1, v)
	return u
}

// UpdateSha1 sets the "sha1" field to the value that was provided on create.
func (u *FileUpsert) UpdateSha1() *FileUpsert {
	u.SetExcluded(file.FieldSha1)
	return u
}

// SetName sets the "name" field.
func (u *FileUpsert) SetName(v string) *FileUpsert {
	u.Set(file.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FileUpsert) UpdateName() *FileUpsert {
	u.SetExcluded(file.FieldName)
	return u
}

// SetSize sets the "size" field.
func (u *FileUpsert) SetSize(v int64) *FileUpsert {
	u.Set(file.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *FileUpsert) UpdateSize() *FileUpsert {
	u.SetExcluded(file.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *FileUpsert) AddSize(v int64) *FileUpsert {
	u.Add(file.FieldSize, v)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *FileUpsert) SetParentID(v string) *FileUpsert {
	u.Set(file.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *FileUpsert) UpdateParentID() *FileUpsert {
	u.SetExcluded(file.FieldParentID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *FileUpsert) SetAccountID(v string) *FileUpsert {
	u.Set(file.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *FileUpsert) UpdateAccountID() *FileUpsert {
	u.SetExcluded(file.FieldAccountID)
	return u
}

// SetRootID sets the "root_id" field.
func (u *FileUpsert) SetRootID(v string) *FileUpsert {
	u.Set(file.FieldRootID, v)
	return u
}

// UpdateRootID sets the "root_id" field to the value that was provided on create.
func (u *FileUpsert) UpdateRootID() *FileUpsert {
	u.SetExcluded(file.FieldRootID)
	return u
}

// SetPath sets the "path" field.
func (u *FileUpsert) SetPath(v string) *FileUpsert {
	u.Set(file.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *FileUpsert) UpdatePath() *FileUpsert {
	u.SetExcluded(file.FieldPath)
	return u
}

// SetScanID sets the "scan_id" field.
func (u *FileUpsert) SetScanID(v string) *FileUpsert {
	u.Set(file.FieldScanID, v)
	return u
}

// UpdateScanID sets the "scan_id" field to the value that was provided on create.
func (u *FileUpsert) UpdateScanID() *FileUpsert {
	u.SetExcluded(file.FieldScanID)
	return u
}

// SetMovieID sets the "movie_id" field.
func (u *FileUpsert) SetMovieID(v int) *FileUpsert {
	u.Set(file.FieldMovieID, v)
	return u
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *FileUpsert) UpdateMovieID() *FileUpsert {
	u.SetExcluded(file.FieldMovieID)
	return u
}

// ClearMovieID clears the value of the "movie_id" field.
func (u *FileUpsert) ClearMovieID() *FileUpsert {
	u.SetNull(file.FieldMovieID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.File.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FileUpsertOne) UpdateNewValues() *FileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(file.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.File.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FileUpsertOne) Ignore() *FileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FileUpsertOne) DoNothing() *FileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FileCreate.OnConflict
// documentation for more info.
func (u *FileUpsertOne) Update(set func(*FileUpsert)) *FileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FileUpsertOne) SetUpdatedAt(v time.Time) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateUpdatedAt() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFileID sets the "file_id" field.
func (u *FileUpsertOne) SetFileID(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateFileID() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateFileID()
	})
}

// SetPickCode sets the "pick_code" field.
func (u *FileUpsertOne) SetPickCode(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetPickCode(v)
	})
}

// UpdatePickCode sets the "pick_code" field to the value that was provided on create.
func (u *FileUpsertOne) UpdatePickCode() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdatePickCode()
	})
}

// SetSha1 sets the "sha1" field.
func (u *FileUpsertOne) SetSha1(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetSha1(v)
	})
}

// UpdateSha1 sets the "sha1" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateSha1() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateSha1()
	})
}

// SetName sets the "name" field.
func (u *FileUpsertOne) SetName(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateName() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateName()
	})
}

// SetSize sets the "size" field.
func (u *FileUpsertOne) SetSize(v int64) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *FileUpsertOne) AddSize(v int64) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateSize() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateSize()
	})
}

// SetParentID sets the "parent_id" field.
func (u *FileUpsertOne) SetParentID(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateParentID() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateParentID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *FileUpsertOne) SetAccountID(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateAccountID() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateAccountID()
	})
}

// SetRootID sets the "root_id" field.
func (u *FileUpsertOne) SetRootID(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetRootID(v)
	})
}

// UpdateRootID sets the "root_id" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateRootID() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateRootID()
	})
}

// SetPath sets the "path" field.
func (u *FileUpsertOne) SetPath(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *FileUpsertOne) UpdatePath() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdatePath()
	})
}

// SetScanID sets the "scan_id" field.
func (u *FileUpsertOne) SetScanID(v string) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetScanID(v)
	})
}

// UpdateScanID sets the "scan_id" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateScanID() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateScanID()
	})
}

// SetMovieID sets the "movie_id" field.
func (u *FileUpsertOne) SetMovieID(v int) *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.SetMovieID(v)
	})
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *FileUpsertOne) UpdateMovieID() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.UpdateMovieID()
	})
}

// ClearMovieID clears the value of the "movie_id" field.
func (u *FileUpsertOne) ClearMovieID() *FileUpsertOne {
	return u.Update(func(s *FileUpsert) {
		s.ClearMovieID()
	})
}

// Exec executes the query.
func (u *FileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FileUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FileUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FileCreateBulk is the builder for creating many File entities in bulk.
type FileCreateBulk struct {
	config
	err      error
	builders []*FileCreate
	conflict []sql.ConflictOption
}

// Save creates the File entities in the database.
func (_c *FileCreateBulk) Save(ctx context.Context) ([]*File, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*File, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileCreateBulk) SaveX(ctx context.Context) []*File {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.File.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FileCreateBulk) OnConflict(opts ...sql.ConflictOption) *FileUpsertBulk {
	_c.conflict = opts
	return &FileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.File.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FileCreateBulk) OnConflictColumns(columns ...string) *FileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FileUpsertBulk{
		create: _c,
	}
}

// FileUpsertBulk is the builder for "upsert"-ing
// a bulk of File nodes.
type FileUpsertBulk struct {
	create *FileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.File.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FileUpsertBulk) UpdateNewValues() *FileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(file.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.File.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FileUpsertBulk) Ignore() *FileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FileUpsertBulk) DoNothing() *FileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FileCreateBulk.OnConflict
// documentation for more info.
func (u *FileUpsertBulk) Update(set func(*FileUpsert)) *FileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FileUpsertBulk) SetUpdatedAt(v time.Time) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateUpdatedAt() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFileID sets the "file_id" field.
func (u *FileUpsertBulk) SetFileID(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateFileID() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateFileID()
	})
}

// SetPickCode sets the "pick_code" field.
func (u *FileUpsertBulk) SetPickCode(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetPickCode(v)
	})
}

// UpdatePickCode sets the "pick_code" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdatePickCode() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdatePickCode()
	})
}

// SetSha1 sets the "sha1" field.
func (u *FileUpsertBulk) SetSha1(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetSha1(v)
	})
}

// UpdateSha1 sets the "sha1" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateSha1() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateSha1()
	})
}

// SetName sets the "name" field.
func (u *FileUpsertBulk) SetName(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateName() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateName()
	})
}

// SetSize sets the "size" field.
func (u *FileUpsertBulk) SetSize(v int64) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *FileUpsertBulk) AddSize(v int64) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateSize() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateSize()
	})
}

// SetParentID sets the "parent_id" field.
func (u *FileUpsertBulk) SetParentID(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateParentID() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateParentID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *FileUpsertBulk) SetAccountID(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateAccountID() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateAccountID()
	})
}

// SetRootID sets the "root_id" field.
func (u *FileUpsertBulk) SetRootID(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetRootID(v)
	})
}

// UpdateRootID sets the "root_id" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateRootID() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateRootID()
	})
}

// SetPath sets the "path" field.
func (u *FileUpsertBulk) SetPath(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdatePath() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdatePath()
	})
}

// SetScanID sets the "scan_id" field.
func (u *FileUpsertBulk) SetScanID(v string) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetScanID(v)
	})
}

// UpdateScanID sets the "scan_id" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateScanID() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateScanID()
	})
}

// SetMovieID sets the "movie_id" field.
func (u *FileUpsertBulk) SetMovieID(v int) *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.SetMovieID(v)
	})
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *FileUpsertBulk) UpdateMovieID() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.UpdateMovieID()
	})
}

// ClearMovieID clears the value of the "movie_id" field.
func (u *FileUpsertBulk) ClearMovieID() *FileUpsertBulk {
	return u.Update(func(s *FileUpsert) {
		s.ClearMovieID()
	})
}

// Exec executes the query.
func (u *FileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
