// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/file"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// FileUpdate is the builder for updating File entities.
type FileUpdate struct {
	config
	hooks    []Hook
	mutation *FileMutation
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdate) Where(ps ...predicate.File) *FileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileUpdate) SetUpdatedAt(v time.Time) *FileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *FileUpdate) SetFileID(v string) *FileUpdate {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *FileUpdate) SetNillableFileID(v *string) *FileUpdate {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// SetPickCode sets the "pick_code" field.
func (_u *FileUpdate) SetPickCode(v string) *FileUpdate {
	_u.mutation.SetPickCode(v)
	return _u
}

// SetNillablePickCode sets the "pick_code" field if the given value is not nil.
func (_u *FileUpdate) SetNillablePickCode(v *string) *FileUpdate {
	if v != nil {
		_u.SetPickCode(*v)
	}
	return _u
}

// SetSha1 sets the "sha1" field.
func (_u *FileUpdate) SetSha1(v string) *FileUpdate {
	_u.mutation.SetSha1(v)
	return _u
}

// SetNillableSha1 sets the "sha1" field if the given value is not nil.
func (_u *FileUpdate) SetNillableSha1(v *string) *FileUpdate {
	if v != nil {
		_u.SetSha1(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FileUpdate) SetName(v string) *FileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FileUpdate) SetNillableName(v *string) *FileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *FileUpdate) SetSize(v int64) *FileUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *FileUpdate) SetNillableSize(v *int64) *FileUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *FileUpdate) AddSize(v int64) *FileUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *FileUpdate) SetParentID(v string) *FileUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *FileUpdate) SetNillableParentID(v *string) *FileUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *FileUpdate) SetAccountID(v string) *FileUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *FileUpdate) SetNillableAccountID(v *string) *FileUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetRootID sets the "root_id" field.
func (_u *FileUpdate) SetRootID(v string) *FileUpdate {
	_u.mutation.SetRootID(v)
	return _u
}

// SetNillableRootID sets the "root_id" field if the given value is not nil.
func (_u *FileUpdate) SetNillableRootID(v *string) *FileUpdate {
	if v != nil {
		_u.SetRootID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *FileUpdate) SetPath(v string) *FileUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *FileUpdate) SetNillablePath(v *string) *FileUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetScanID sets the "scan_id" field.
func (_u *FileUpdate) SetScanID(v string) *FileUpdate {
	_u.mutation.SetScanID(v)
	return _u
}

// SetNillableScanID sets the "scan_id" field if the given value is not nil.
func (_u *FileUpdate) SetNillableScanID(v *string) *FileUpdate {
	if v != nil {
		_u.SetScanID(*v)
	}
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *FileUpdate) SetMovieID(v int) *FileUpdate {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *FileUpdate) SetNillableMovieID(v *int) *FileUpdate {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// ClearMovieID clears the value of the "movie_id" field.
func (_u *FileUpdate) ClearMovieID() *FileUpdate {
	_u.mutation.ClearMovieID()
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *FileUpdate) SetMovie(v *Movie) *FileUpdate {
	return _u.SetMovieID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdate) Mutation() *FileMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *FileUpdate) ClearMovie() *FileUpdate {
	_u.mutation.ClearMovie()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := file.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUpdate) check() error {
	if v, ok := _u.mutation.FileID(); ok {
		if err := file.FileIDValidator(v); err != nil {
			return &ValidationError{Name: "file_id", err: fmt.Errorf(`ent: validator failed for field "File.file_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := file.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "File.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := file.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "File.size": %w`, err)}
		}
	}
	return nil
}

func (_u *FileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(file.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(file.FieldFileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PickCode(); ok {
		_spec.SetField(file.FieldPickCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha1(); ok {
		_spec.SetField(file.FieldSha1, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(file.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(file.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(file.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(file.FieldParentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(file.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootID(); ok {
		_spec.SetField(file.FieldRootID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(file.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScanID(); ok {
		_spec.SetField(file.FieldScanID, field.TypeString, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.MovieTable,
			Columns: []string{file.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.MovieTable,
			Columns: []string{file.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileUpdateOne is the builder for updating a single File entity.
type FileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FileUpdateOne) SetUpdatedAt(v time.Time) *FileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *FileUpdateOne) SetFileID(v string) *FileUpdateOne {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableFileID(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// SetPickCode sets the "pick_code" field.
func (_u *FileUpdateOne) SetPickCode(v string) *FileUpdateOne {
	_u.mutation.SetPickCode(v)
	return _u
}

// SetNillablePickCode sets the "pick_code" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillablePickCode(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetPickCode(*v)
	}
	return _u
}

// SetSha1 sets the "sha1" field.
func (_u *FileUpdateOne) SetSha1(v string) *FileUpdateOne {
	_u.mutation.SetSha1(v)
	return _u
}

// SetNillableSha1 sets the "sha1" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableSha1(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetSha1(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FileUpdateOne) SetName(v string) *FileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableName(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *FileUpdateOne) SetSize(v int64) *FileUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableSize(v *int64) *FileUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *FileUpdateOne) AddSize(v int64) *FileUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *FileUpdateOne) SetParentID(v string) *FileUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableParentID(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *FileUpdateOne) SetAccountID(v string) *FileUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableAccountID(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetRootID sets the "root_id" field.
func (_u *FileUpdateOne) SetRootID(v string) *FileUpdateOne {
	_u.mutation.SetRootID(v)
	return _u
}

// SetNillableRootID sets the "root_id" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableRootID(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetRootID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *FileUpdateOne) SetPath(v string) *FileUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillablePath(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetScanID sets the "scan_id" field.
func (_u *FileUpdateOne) SetScanID(v string) *FileUpdateOne {
	_u.mutation.SetScanID(v)
	return _u
}

// SetNillableScanID sets the "scan_id" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableScanID(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetScanID(*v)
	}
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *FileUpdateOne) SetMovieID(v int) *FileUpdateOne {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableMovieID(v *int) *FileUpdateOne {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// ClearMovieID clears the value of the "movie_id" field.
func (_u *FileUpdateOne) ClearMovieID() *FileUpdateOne {
	_u.mutation.ClearMovieID()
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *FileUpdateOne) SetMovie(v *Movie) *FileUpdateOne {
	return _u.SetMovieID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdateOne) Mutation() *FileMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *FileUpdateOne) ClearMovie() *FileUpdateOne {
	_u.mutation.ClearMovie()
	return _u
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdateOne) Where(ps ...predicate.File) *FileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileUpdateOne) Select(field string, fields ...string) *FileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated File entity.
func (_u *FileUpdateOne) Save(ctx context.Context) (*File, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdateOne) SaveX(ctx context.Context) *File {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := file.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUpdateOne) check() error {
	if v, ok := _u.mutation.FileID(); ok {
		if err := file.FileIDValidator(v); err != nil {
			return &ValidationError{Name: "file_id", err: fmt.Errorf(`ent: validator failed for field "File.file_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := file.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "File.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := file.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "File.size": %w`, err)}
		}
	}
	return nil
}

func (_u *FileUpdateOne) sqlSave(ctx context.Context) (_node *File, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "File.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, file.FieldID)
		for _, f := range fields {
			if !file.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != file.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(file.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(file.FieldFileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PickCode(); ok {
		_spec.SetField(file.FieldPickCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha1(); ok {
		_spec.SetField(file.FieldSha1, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(file.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(file.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(file.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(file.FieldParentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(file.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootID(); ok {
		_spec.SetField(file.FieldRootID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(file.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScanID(); ok {
		_spec.SetField(file.FieldScanID, field.TypeString, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.MovieTable,
			Columns: []string{file.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.MovieTable,
			Columns: []string{file.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &File{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
