// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json/jsontext"
	"time"

	"github.com/ppxb/miyabi/internal/ent/actor"
	"github.com/ppxb/miyabi/internal/ent/file"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/schema"
	"github.com/ppxb/miyabi/internal/ent/setting"
	"github.com/ppxb/miyabi/internal/ent/tag"
	"github.com/ppxb/miyabi/internal/ent/task"
	"github.com/ppxb/miyabi/internal/ent/watchhistory"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	actorMixin := schema.Actor{}.Mixin()
	actorMixinFields0 := actorMixin[0].Fields()
	_ = actorMixinFields0
	actorFields := schema.Actor{}.Fields()
	_ = actorFields
	// actorDescCreatedAt is the schema descriptor for created_at field.
	actorDescCreatedAt := actorMixinFields0[0].Descriptor()
	// actor.DefaultCreatedAt holds the default value on creation for the created_at field.
	actor.DefaultCreatedAt = actorDescCreatedAt.Default.(func() time.Time)
	// actorDescUpdatedAt is the schema descriptor for updated_at field.
	actorDescUpdatedAt := actorMixinFields0[1].Descriptor()
	// actor.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	actor.DefaultUpdatedAt = actorDescUpdatedAt.Default.(func() time.Time)
	// actor.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	actor.UpdateDefaultUpdatedAt = actorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// actorDescJavdbID is the schema descriptor for javdb_id field.
	actorDescJavdbID := actorFields[0].Descriptor()
	// actor.JavdbIDValidator is a validator for the "javdb_id" field. It is called by the builders before save.
	actor.JavdbIDValidator = actorDescJavdbID.Validators[0].(func(string) error)
	// actorDescName is the schema descriptor for name field.
	actorDescName := actorFields[1].Descriptor()
	// actor.NameValidator is a validator for the "name" field. It is called by the builders before save.
	actor.NameValidator = actorDescName.Validators[0].(func(string) error)
	fileMixin := schema.File{}.Mixin()
	fileMixinFields0 := fileMixin[0].Fields()
	_ = fileMixinFields0
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileMixinFields0[0].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescUpdatedAt is the schema descriptor for updated_at field.
	fileDescUpdatedAt := fileMixinFields0[1].Descriptor()
	// file.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	file.DefaultUpdatedAt = fileDescUpdatedAt.Default.(func() time.Time)
	// file.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	file.UpdateDefaultUpdatedAt = fileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// fileDescFileID is the schema descriptor for file_id field.
	fileDescFileID := fileFields[0].Descriptor()
	// file.FileIDValidator is a validator for the "file_id" field. It is called by the builders before save.
	file.FileIDValidator = fileDescFileID.Validators[0].(func(string) error)
	// fileDescPickCode is the schema descriptor for pick_code field.
	fileDescPickCode := fileFields[1].Descriptor()
	// file.DefaultPickCode holds the default value on creation for the pick_code field.
	file.DefaultPickCode = fileDescPickCode.Default.(string)
	// fileDescSha1 is the schema descriptor for sha1 field.
	fileDescSha1 := fileFields[2].Descriptor()
	// file.DefaultSha1 holds the default value on creation for the sha1 field.
	file.DefaultSha1 = fileDescSha1.Default.(string)
	// fileDescName is the schema descriptor for name field.
	fileDescName := fileFields[3].Descriptor()
	// file.NameValidator is a validator for the "name" field. It is called by the builders before save.
	file.NameValidator = fileDescName.Validators[0].(func(string) error)
	// fileDescSize is the schema descriptor for size field.
	fileDescSize := fileFields[4].Descriptor()
	// file.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	file.SizeValidator = fileDescSize.Validators[0].(func(int64) error)
	// fileDescParentID is the schema descriptor for parent_id field.
	fileDescParentID := fileFields[5].Descriptor()
	// file.DefaultParentID holds the default value on creation for the parent_id field.
	file.DefaultParentID = fileDescParentID.Default.(string)
	// fileDescAccountID is the schema descriptor for account_id field.
	fileDescAccountID := fileFields[6].Descriptor()
	// file.DefaultAccountID holds the default value on creation for the account_id field.
	file.DefaultAccountID = fileDescAccountID.Default.(string)
	// fileDescRootID is the schema descriptor for root_id field.
	fileDescRootID := fileFields[7].Descriptor()
	// file.DefaultRootID holds the default value on creation for the root_id field.
	file.DefaultRootID = fileDescRootID.Default.(string)
	// fileDescPath is the schema descriptor for path field.
	fileDescPath := fileFields[8].Descriptor()
	// file.DefaultPath holds the default value on creation for the path field.
	file.DefaultPath = fileDescPath.Default.(string)
	// fileDescScanID is the schema descriptor for scan_id field.
	fileDescScanID := fileFields[9].Descriptor()
	// file.DefaultScanID holds the default value on creation for the scan_id field.
	file.DefaultScanID = fileDescScanID.Default.(string)
	movieMixin := schema.Movie{}.Mixin()
	movieMixinFields0 := movieMixin[0].Fields()
	_ = movieMixinFields0
	movieFields := schema.Movie{}.Fields()
	_ = movieFields
	// movieDescCreatedAt is the schema descriptor for created_at field.
	movieDescCreatedAt := movieMixinFields0[0].Descriptor()
	// movie.DefaultCreatedAt holds the default value on creation for the created_at field.
	movie.DefaultCreatedAt = movieDescCreatedAt.Default.(func() time.Time)
	// movieDescUpdatedAt is the schema descriptor for updated_at field.
	movieDescUpdatedAt := movieMixinFields0[1].Descriptor()
	// movie.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	movie.DefaultUpdatedAt = movieDescUpdatedAt.Default.(func() time.Time)
	// movie.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	movie.UpdateDefaultUpdatedAt = movieDescUpdatedAt.UpdateDefault.(func() time.Time)
	// movieDescCode is the schema descriptor for code field.
	movieDescCode := movieFields[0].Descriptor()
	// movie.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	movie.CodeValidator = movieDescCode.Validators[0].(func(string) error)
	// movieDescTitle is the schema descriptor for title field.
	movieDescTitle := movieFields[2].Descriptor()
	// movie.DefaultTitle holds the default value on creation for the title field.
	movie.DefaultTitle = movieDescTitle.Default.(string)
	// movieDescFanarts is the schema descriptor for fanarts field.
	movieDescFanarts := movieFields[14].Descriptor()
	// movie.DefaultFanarts holds the default value on creation for the fanarts field.
	movie.DefaultFanarts = movieDescFanarts.Default.(func() []string)
	// movieDescWatched is the schema descriptor for watched field.
	movieDescWatched := movieFields[16].Descriptor()
	// movie.DefaultWatched holds the default value on creation for the watched field.
	movie.DefaultWatched = movieDescWatched.Default.(bool)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
	tagMixin := schema.Tag{}.Mixin()
	tagMixinFields0 := tagMixin[0].Fields()
	_ = tagMixinFields0
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescCreatedAt is the schema descriptor for created_at field.
	tagDescCreatedAt := tagMixinFields0[0].Descriptor()
	// tag.DefaultCreatedAt holds the default value on creation for the created_at field.
	tag.DefaultCreatedAt = tagDescCreatedAt.Default.(func() time.Time)
	// tagDescUpdatedAt is the schema descriptor for updated_at field.
	tagDescUpdatedAt := tagMixinFields0[1].Descriptor()
	// tag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tag.DefaultUpdatedAt = tagDescUpdatedAt.Default.(func() time.Time)
	// tag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tag.UpdateDefaultUpdatedAt = tagDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tagDescJavdbID is the schema descriptor for javdb_id field.
	tagDescJavdbID := tagFields[0].Descriptor()
	// tag.JavdbIDValidator is a validator for the "javdb_id" field. It is called by the builders before save.
	tag.JavdbIDValidator = tagDescJavdbID.Validators[0].(func(string) error)
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[1].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	// tagDescCategoryID is the schema descriptor for category_id field.
	tagDescCategoryID := tagFields[3].Descriptor()
	// tag.CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	tag.CategoryIDValidator = tagDescCategoryID.Validators[0].(func(string) error)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskMixinFields0[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// taskDescType is the schema descriptor for type field.
	taskDescType := taskFields[0].Descriptor()
	// task.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	task.TypeValidator = taskDescType.Validators[0].(func(string) error)
	// taskDescPayload is the schema descriptor for payload field.
	taskDescPayload := taskFields[2].Descriptor()
	// task.DefaultPayload holds the default value on creation for the payload field.
	task.DefaultPayload = taskDescPayload.Default.(func() jsontext.Value)
	// taskDescProgress is the schema descriptor for progress field.
	taskDescProgress := taskFields[3].Descriptor()
	// task.DefaultProgress holds the default value on creation for the progress field.
	task.DefaultProgress = taskDescProgress.Default.(int)
	// task.ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	task.ProgressValidator = taskDescProgress.Validators[0].(func(int) error)
	watchhistoryFields := schema.WatchHistory{}.Fields()
	_ = watchhistoryFields
	// watchhistoryDescAccountID is the schema descriptor for account_id field.
	watchhistoryDescAccountID := watchhistoryFields[0].Descriptor()
	// watchhistory.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	watchhistory.AccountIDValidator = watchhistoryDescAccountID.Validators[0].(func(string) error)
	// watchhistoryDescRootID is the schema descriptor for root_id field.
	watchhistoryDescRootID := watchhistoryFields[1].Descriptor()
	// watchhistory.RootIDValidator is a validator for the "root_id" field. It is called by the builders before save.
	watchhistory.RootIDValidator = watchhistoryDescRootID.Validators[0].(func(string) error)
	// watchhistoryDescMovieID is the schema descriptor for movie_id field.
	watchhistoryDescMovieID := watchhistoryFields[2].Descriptor()
	// watchhistory.MovieIDValidator is a validator for the "movie_id" field. It is called by the builders before save.
	watchhistory.MovieIDValidator = watchhistoryDescMovieID.Validators[0].(func(int) error)
	// watchhistoryDescWatchedAt is the schema descriptor for watched_at field.
	watchhistoryDescWatchedAt := watchhistoryFields[3].Descriptor()
	// watchhistory.DefaultWatchedAt holds the default value on creation for the watched_at field.
	watchhistory.DefaultWatchedAt = watchhistoryDescWatchedAt.Default.(func() time.Time)
	// watchhistoryDescSessionID is the schema descriptor for session_id field.
	watchhistoryDescSessionID := watchhistoryFields[4].Descriptor()
	// watchhistory.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	watchhistory.SessionIDValidator = watchhistoryDescSessionID.Validators[0].(func(string) error)
	// watchhistoryDescFileID is the schema descriptor for file_id field.
	watchhistoryDescFileID := watchhistoryFields[5].Descriptor()
	// watchhistory.DefaultFileID holds the default value on creation for the file_id field.
	watchhistory.DefaultFileID = watchhistoryDescFileID.Default.(string)
	// watchhistoryDescPosition is the schema descriptor for position field.
	watchhistoryDescPosition := watchhistoryFields[6].Descriptor()
	// watchhistory.DefaultPosition holds the default value on creation for the position field.
	watchhistory.DefaultPosition = watchhistoryDescPosition.Default.(float64)
	// watchhistoryDescDuration is the schema descriptor for duration field.
	watchhistoryDescDuration := watchhistoryFields[7].Descriptor()
	// watchhistory.DefaultDuration holds the default value on creation for the duration field.
	watchhistory.DefaultDuration = watchhistoryDescDuration.Default.(float64)
	// watchhistoryDescProgressVersion is the schema descriptor for progress_version field.
	watchhistoryDescProgressVersion := watchhistoryFields[8].Descriptor()
	// watchhistory.DefaultProgressVersion holds the default value on creation for the progress_version field.
	watchhistory.DefaultProgressVersion = watchhistoryDescProgressVersion.Default.(int)
	// watchhistory.ProgressVersionValidator is a validator for the "progress_version" field. It is called by the builders before save.
	watchhistory.ProgressVersionValidator = watchhistoryDescProgressVersion.Validators[0].(func(int) error)
}
