// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/predicate"
	"github.com/ppxb/miyabi/internal/ent/subscription"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdate) SetUpdatedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *SubscriptionUpdate) SetKind(v subscription.Kind) *SubscriptionUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableKind(v *subscription.Kind) *SubscriptionUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *SubscriptionUpdate) SetTargetID(v string) *SubscriptionUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableTargetID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *SubscriptionUpdate) SetCode(v string) *SubscriptionUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCode(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SubscriptionUpdate) SetTitle(v string) *SubscriptionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableTitle(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *SubscriptionUpdate) SetCover(v string) *SubscriptionUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCover(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *SubscriptionUpdate) SetReleaseDate(v string) *SubscriptionUpdate {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableReleaseDate(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// SetOriginID sets the "origin_id" field.
func (_u *SubscriptionUpdate) SetOriginID(v int) *SubscriptionUpdate {
	_u.mutation.ResetOriginID()
	_u.mutation.SetOriginID(v)
	return _u
}

// SetNillableOriginID sets the "origin_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableOriginID(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetOriginID(*v)
	}
	return _u
}

// AddOriginID adds value to the "origin_id" field.
func (_u *SubscriptionUpdate) AddOriginID(v int) *SubscriptionUpdate {
	_u.mutation.AddOriginID(v)
	return _u
}

// ClearOriginID clears the value of the "origin_id" field.
func (_u *SubscriptionUpdate) ClearOriginID() *SubscriptionUpdate {
	_u.mutation.ClearOriginID()
	return _u
}

// SetAutoDownload sets the "auto_download" field.
func (_u *SubscriptionUpdate) SetAutoDownload(v bool) *SubscriptionUpdate {
	_u.mutation.SetAutoDownload(v)
	return _u
}

// SetNillableAutoDownload sets the "auto_download" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableAutoDownload(v *bool) *SubscriptionUpdate {
	if v != nil {
		_u.SetAutoDownload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdate) SetStatus(v subscription.Status) *SubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStatus(v *subscription.Status) *SubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCursor sets the "cursor" field.
func (_u *SubscriptionUpdate) SetCursor(v string) *SubscriptionUpdate {
	_u.mutation.SetCursor(v)
	return _u
}

// SetNillableCursor sets the "cursor" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCursor(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetCursor(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *SubscriptionUpdate) SetHash(v string) *SubscriptionUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableHash(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *SubscriptionUpdate) SetTaskID(v int) *SubscriptionUpdate {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableTaskID(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *SubscriptionUpdate) AddTaskID(v int) *SubscriptionUpdate {
	_u.mutation.AddTaskID(v)
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *SubscriptionUpdate) ClearTaskID() *SubscriptionUpdate {
	_u.mutation.ClearTaskID()
	return _u
}

// SetNextCheckAt sets the "next_check_at" field.
func (_u *SubscriptionUpdate) SetNextCheckAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetNextCheckAt(v)
	return _u
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableNextCheckAt(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetNextCheckAt(*v)
	}
	return _u
}

// ClearNextCheckAt clears the value of the "next_check_at" field.
func (_u *SubscriptionUpdate) ClearNextCheckAt() *SubscriptionUpdate {
	_u.mutation.ClearNextCheckAt()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *SubscriptionUpdate) SetLastCheckedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableLastCheckedAt(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *SubscriptionUpdate) ClearLastCheckedAt() *SubscriptionUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetChecks sets the "checks" field.
func (_u *SubscriptionUpdate) SetChecks(v int) *SubscriptionUpdate {
	_u.mutation.ResetChecks()
	_u.mutation.SetChecks(v)
	return _u
}

// SetNillableChecks sets the "checks" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableChecks(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetChecks(*v)
	}
	return _u
}

// AddChecks adds value to the "checks" field.
func (_u *SubscriptionUpdate) AddChecks(v int) *SubscriptionUpdate {
	_u.mutation.AddChecks(v)
	return _u
}

// SetError sets the "error" field.
func (_u *SubscriptionUpdate) SetError(v string) *SubscriptionUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableError(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *SubscriptionUpdate) ClearError() *SubscriptionUpdate {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := subscription.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Subscription.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := subscription.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.target_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checks(); ok {
		if err := subscription.ChecksValidator(v); err != nil {
			return &ValidationError{Name: "checks", err: fmt.Errorf(`ent: validator failed for field "Subscription.checks": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(subscription.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(subscription.FieldTargetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(subscription.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(subscription.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(subscription.FieldCover, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(subscription.FieldReleaseDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginID(); ok {
		_spec.SetField(subscription.FieldOriginID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOriginID(); ok {
		_spec.AddField(subscription.FieldOriginID, field.TypeInt, value)
	}
	if _u.mutation.OriginIDCleared() {
		_spec.ClearField(subscription.FieldOriginID, field.TypeInt)
	}
	if value, ok := _u.mutation.AutoDownload(); ok {
		_spec.SetField(subscription.FieldAutoDownload, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Cursor(); ok {
		_spec.SetField(subscription.FieldCursor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(subscription.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(subscription.FieldTaskID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(subscription.FieldTaskID, field.TypeInt, value)
	}
	if _u.mutation.TaskIDCleared() {
		_spec.ClearField(subscription.FieldTaskID, field.TypeInt)
	}
	if value, ok := _u.mutation.NextCheckAt(); ok {
		_spec.SetField(subscription.FieldNextCheckAt, field.TypeTime, value)
	}
	if _u.mutation.NextCheckAtCleared() {
		_spec.ClearField(subscription.FieldNextCheckAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(subscription.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(subscription.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Checks(); ok {
		_spec.SetField(subscription.FieldChecks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecks(); ok {
		_spec.AddField(subscription.FieldChecks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(subscription.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(subscription.FieldError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *SubscriptionUpdateOne) SetKind(v subscription.Kind) *SubscriptionUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableKind(v *subscription.Kind) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *SubscriptionUpdateOne) SetTargetID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableTargetID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *SubscriptionUpdateOne) SetCode(v string) *SubscriptionUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCode(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SubscriptionUpdateOne) SetTitle(v string) *SubscriptionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableTitle(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *SubscriptionUpdateOne) SetCover(v string) *SubscriptionUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCover(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *SubscriptionUpdateOne) SetReleaseDate(v string) *SubscriptionUpdateOne {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableReleaseDate(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// SetOriginID sets the "origin_id" field.
func (_u *SubscriptionUpdateOne) SetOriginID(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetOriginID()
	_u.mutation.SetOriginID(v)
	return _u
}

// SetNillableOriginID sets the "origin_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableOriginID(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetOriginID(*v)
	}
	return _u
}

// AddOriginID adds value to the "origin_id" field.
func (_u *SubscriptionUpdateOne) AddOriginID(v int) *SubscriptionUpdateOne {
	_u.mutation.AddOriginID(v)
	return _u
}

// ClearOriginID clears the value of the "origin_id" field.
func (_u *SubscriptionUpdateOne) ClearOriginID() *SubscriptionUpdateOne {
	_u.mutation.ClearOriginID()
	return _u
}

// SetAutoDownload sets the "auto_download" field.
func (_u *SubscriptionUpdateOne) SetAutoDownload(v bool) *SubscriptionUpdateOne {
	_u.mutation.SetAutoDownload(v)
	return _u
}

// SetNillableAutoDownload sets the "auto_download" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableAutoDownload(v *bool) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetAutoDownload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdateOne) SetStatus(v subscription.Status) *SubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStatus(v *subscription.Status) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCursor sets the "cursor" field.
func (_u *SubscriptionUpdateOne) SetCursor(v string) *SubscriptionUpdateOne {
	_u.mutation.SetCursor(v)
	return _u
}

// SetNillableCursor sets the "cursor" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCursor(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCursor(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *SubscriptionUpdateOne) SetHash(v string) *SubscriptionUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableHash(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *SubscriptionUpdateOne) SetTaskID(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableTaskID(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *SubscriptionUpdateOne) AddTaskID(v int) *SubscriptionUpdateOne {
	_u.mutation.AddTaskID(v)
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *SubscriptionUpdateOne) ClearTaskID() *SubscriptionUpdateOne {
	_u.mutation.ClearTaskID()
	return _u
}

// SetNextCheckAt sets the "next_check_at" field.
func (_u *SubscriptionUpdateOne) SetNextCheckAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetNextCheckAt(v)
	return _u
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableNextCheckAt(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetNextCheckAt(*v)
	}
	return _u
}

// ClearNextCheckAt clears the value of the "next_check_at" field.
func (_u *SubscriptionUpdateOne) ClearNextCheckAt() *SubscriptionUpdateOne {
	_u.mutation.ClearNextCheckAt()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *SubscriptionUpdateOne) SetLastCheckedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableLastCheckedAt(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *SubscriptionUpdateOne) ClearLastCheckedAt() *SubscriptionUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetChecks sets the "checks" field.
func (_u *SubscriptionUpdateOne) SetChecks(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetChecks()
	_u.mutation.SetChecks(v)
	return _u
}

// SetNillableChecks sets the "checks" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableChecks(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetChecks(*v)
	}
	return _u
}

// AddChecks adds value to the "checks" field.
func (_u *SubscriptionUpdateOne) AddChecks(v int) *SubscriptionUpdateOne {
	_u.mutation.AddChecks(v)
	return _u
}

// SetError sets the "error" field.
func (_u *SubscriptionUpdateOne) SetError(v string) *SubscriptionUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableError(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *SubscriptionUpdateOne) ClearError() *SubscriptionUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := subscription.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Subscription.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := subscription.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.target_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checks(); ok {
		if err := subscription.ChecksValidator(v); err != nil {
			return &ValidationError{Name: "checks", err: fmt.Errorf(`ent: validator failed for field "Subscription.checks": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(subscription.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(subscription.FieldTargetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(subscription.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(subscription.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(subscription.FieldCover, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(subscription.FieldReleaseDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginID(); ok {
		_spec.SetField(subscription.FieldOriginID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOriginID(); ok {
		_spec.AddField(subscription.FieldOriginID, field.TypeInt, value)
	}
	if _u.mutation.OriginIDCleared() {
		_spec.ClearField(subscription.FieldOriginID, field.TypeInt)
	}
	if value, ok := _u.mutation.AutoDownload(); ok {
		_spec.SetField(subscription.FieldAutoDownload, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Cursor(); ok {
		_spec.SetField(subscription.FieldCursor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(subscription.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(subscription.FieldTaskID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(subscription.FieldTaskID, field.TypeInt, value)
	}
	if _u.mutation.TaskIDCleared() {
		_spec.ClearField(subscription.FieldTaskID, field.TypeInt)
	}
	if value, ok := _u.mutation.NextCheckAt(); ok {
		_spec.SetField(subscription.FieldNextCheckAt, field.TypeTime, value)
	}
	if _u.mutation.NextCheckAtCleared() {
		_spec.ClearField(subscription.FieldNextCheckAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(subscription.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(subscription.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Checks(); ok {
		_spec.SetField(subscription.FieldChecks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecks(); ok {
		_spec.AddField(subscription.FieldChecks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(subscription.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(subscription.FieldError, field.TypeString)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
