// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/subtitle"
)

// SubtitleCreate is the builder for creating a Subtitle entity.
type SubtitleCreate struct {
	config
	mutation *SubtitleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubtitleCreate) SetCreatedAt(v time.Time) *SubtitleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableCreatedAt(v *time.Time) *SubtitleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubtitleCreate) SetUpdatedAt(v time.Time) *SubtitleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableUpdatedAt(v *time.Time) *SubtitleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMovieID sets the "movie_id" field.
func (_c *SubtitleCreate) SetMovieID(v int) *SubtitleCreate {
	_c.mutation.SetMovieID(v)
	return _c
}

// SetFileID sets the "file_id" field.
func (_c *SubtitleCreate) SetFileID(v string) *SubtitleCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableFileID(v *string) *SubtitleCreate {
	if v != nil {
		_c.SetFileID(*v)
	}
	return _c
}

// SetPickCode sets the "pick_code" field.
func (_c *SubtitleCreate) SetPickCode(v string) *SubtitleCreate {
	_c.mutation.SetPickCode(v)
	return _c
}

// SetNillablePickCode sets the "pick_code" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillablePickCode(v *string) *SubtitleCreate {
	if v != nil {
		_c.SetPickCode(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SubtitleCreate) SetName(v string) *SubtitleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *SubtitleCreate) SetLanguage(v string) *SubtitleCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableLanguage(v *string) *SubtitleCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetFormat sets the "format" field.
func (_c *SubtitleCreate) SetFormat(v string) *SubtitleCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableFormat(v *string) *SubtitleCreate {
	if v != nil {
		_c.SetFormat(*v)
	}
	return _c
}

// SetVersionTag sets the "version_tag" field.
func (_c *SubtitleCreate) SetVersionTag(v string) *SubtitleCreate {
	_c.mutation.SetVersionTag(v)
	return _c
}

// SetNillableVersionTag sets the "version_tag" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableVersionTag(v *string) *SubtitleCreate {
	if v != nil {
		_c.SetVersionTag(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *SubtitleCreate) SetSource(v string) *SubtitleCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableSource(v *string) *SubtitleCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *SubtitleCreate) SetSourceURL(v string) *SubtitleCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableSourceURL(v *string) *SubtitleCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetStoragePath sets the "storage_path" field.
func (_c *SubtitleCreate) SetStoragePath(v string) *SubtitleCreate {
	_c.mutation.SetStoragePath(v)
	return _c
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_c *SubtitleCreate) SetNillableStoragePath(v *string) *SubtitleCreate {
	if v != nil {
		_c.SetStoragePath(*v)
	}
	return _c
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_c *SubtitleCreate) SetMovie(v *Movie) *SubtitleCreate {
	return _c.SetMovieID(v.ID)
}

// Mutation returns the SubtitleMutation object of the builder.
func (_c *SubtitleCreate) Mutation() *SubtitleMutation {
	return _c.mutation
}

// Save creates the Subtitle in the database.
func (_c *SubtitleCreate) Save(ctx context.Context) (*Subtitle, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubtitleCreate) SaveX(ctx context.Context) *Subtitle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubtitleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubtitleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubtitleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subtitle.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subtitle.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.FileID(); !ok {
		v := subtitle.DefaultFileID
		_c.mutation.SetFileID(v)
	}
	if _, ok := _c.mutation.PickCode(); !ok {
		v := subtitle.DefaultPickCode
		_c.mutation.SetPickCode(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := subtitle.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.Format(); !ok {
		v := subtitle.DefaultFormat
		_c.mutation.SetFormat(v)
	}
	if _, ok := _c.mutation.VersionTag(); !ok {
		v := subtitle.DefaultVersionTag
		_c.mutation.SetVersionTag(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := subtitle.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		v := subtitle.DefaultSourceURL
		_c.mutation.SetSourceURL(v)
	}
	if _, ok := _c.mutation.StoragePath(); !ok {
		v := subtitle.DefaultStoragePath
		_c.mutation.SetStoragePath(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubtitleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Subtitle.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Subtitle.updated_at"`)}
	}
	if _, ok := _c.mutation.MovieID(); !ok {
		return &ValidationError{Name: "movie_id", err: errors.New(`ent: missing required field "Subtitle.movie_id"`)}
	}
	if v, ok := _c.mutation.MovieID(); ok {
		if err := subtitle.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "Subtitle.movie_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "Subtitle.file_id"`)}
	}
	if _, ok := _c.mutation.PickCode(); !ok {
		return &ValidationError{Name: "pick_code", err: errors.New(`ent: missing required field "Subtitle.pick_code"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Subtitle.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := subtitle.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Subtitle.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "Subtitle.language"`)}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "Subtitle.format"`)}
	}
	if _, ok := _c.mutation.VersionTag(); !ok {
		return &ValidationError{Name: "version_tag", err: errors.New(`ent: missing required field "Subtitle.version_tag"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Subtitle.source"`)}
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		return &ValidationError{Name: "source_url", err: errors.New(`ent: missing required field "Subtitle.source_url"`)}
	}
	if _, ok := _c.mutation.StoragePath(); !ok {
		return &ValidationError{Name: "storage_path", err: errors.New(`ent: missing required field "Subtitle.storage_path"`)}
	}
	if len(_c.mutation.MovieIDs()) == 0 {
		return &ValidationError{Name: "movie", err: errors.New(`ent: missing required edge "Subtitle.movie"`)}
	}
	return nil
}

func (_c *SubtitleCreate) sqlSave(ctx context.Context) (*Subtitle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubtitleCreate) createSpec() (*Subtitle, *sqlgraph.CreateSpec) {
	var (
		_node = &Subtitle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subtitle.Table, sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subtitle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subtitle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FileID(); ok {
		_spec.SetField(subtitle.FieldFileID, field.TypeString, value)
		_node.FileID = value
	}
	if value, ok := _c.mutation.PickCode(); ok {
		_spec.SetField(subtitle.FieldPickCode, field.TypeString, value)
		_node.PickCode = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subtitle.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(subtitle.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(subtitle.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.VersionTag(); ok {
		_spec.SetField(subtitle.FieldVersionTag, field.TypeString, value)
		_node.VersionTag = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(subtitle.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(subtitle.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.StoragePath(); ok {
		_spec.SetField(subtitle.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if nodes := _c.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MovieTable,
			Columns: []string{subtitle.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MovieID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Subtitle.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubtitleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubtitleCreate) OnConflict(opts ...sql.ConflictOption) *SubtitleUpsertOne {
	_c.conflict = opts
	return &SubtitleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Subtitle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubtitleCreate) OnConflictColumns(columns ...string) *SubtitleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubtitleUpsertOne{
		create: _c,
	}
}

type (
	// SubtitleUpsertOne is the builder for "upsert"-ing
	//  one Subtitle node.
	SubtitleUpsertOne struct {
		create *SubtitleCreate
	}

	// SubtitleUpsert is the "OnConflict" setter.
	SubtitleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubtitleUpsert) SetUpdatedAt(v time.Time) *SubtitleUpsert {
	u.Set(subtitle.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateUpdatedAt() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldUpdatedAt)
	return u
}

// SetMovieID sets the "movie_id" field.
func (u *SubtitleUpsert) SetMovieID(v int) *SubtitleUpsert {
	u.Set(subtitle.FieldMovieID, v)
	return u
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateMovieID() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldMovieID)
	return u
}

// SetFileID sets the "file_id" field.
func (u *SubtitleUpsert) SetFileID(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateFileID() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldFileID)
	return u
}

// SetPickCode sets the "pick_code" field.
func (u *SubtitleUpsert) SetPickCode(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldPickCode, v)
	return u
}

// UpdatePickCode sets the "pick_code" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdatePickCode() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldPickCode)
	return u
}

// SetName sets the "name" field.
func (u *SubtitleUpsert) SetName(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateName() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldName)
	return u
}

// SetLanguage sets the "language" field.
func (u *SubtitleUpsert) SetLanguage(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateLanguage() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldLanguage)
	return u
}

// SetFormat sets the "format" field.
func (u *SubtitleUpsert) SetFormat(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldFormat, v)
	return u
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateFormat() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldFormat)
	return u
}

// SetVersionTag sets the "version_tag" field.
func (u *SubtitleUpsert) SetVersionTag(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldVersionTag, v)
	return u
}

// UpdateVersionTag sets the "version_tag" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateVersionTag() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldVersionTag)
	return u
}

// SetSource sets the "source" field.
func (u *SubtitleUpsert) SetSource(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateSource() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldSource)
	return u
}

// SetSourceURL sets the "source_url" field.
func (u *SubtitleUpsert) SetSourceURL(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldSourceURL, v)
	return u
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateSourceURL() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldSourceURL)
	return u
}

// SetStoragePath sets the "storage_path" field.
func (u *SubtitleUpsert) SetStoragePath(v string) *SubtitleUpsert {
	u.Set(subtitle.FieldStoragePath, v)
	return u
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *SubtitleUpsert) UpdateStoragePath() *SubtitleUpsert {
	u.SetExcluded(subtitle.FieldStoragePath)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Subtitle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubtitleUpsertOne) UpdateNewValues() *SubtitleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subtitle.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Subtitle.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubtitleUpsertOne) Ignore() *SubtitleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubtitleUpsertOne) DoNothing() *SubtitleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubtitleCreate.OnConflict
// documentation for more info.
func (u *SubtitleUpsertOne) Update(set func(*SubtitleUpsert)) *SubtitleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubtitleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubtitleUpsertOne) SetUpdatedAt(v time.Time) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateUpdatedAt() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMovieID sets the "movie_id" field.
func (u *SubtitleUpsertOne) SetMovieID(v int) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetMovieID(v)
	})
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateMovieID() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateMovieID()
	})
}

// SetFileID sets the "file_id" field.
func (u *SubtitleUpsertOne) SetFileID(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateFileID() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateFileID()
	})
}

// SetPickCode sets the "pick_code" field.
func (u *SubtitleUpsertOne) SetPickCode(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetPickCode(v)
	})
}

// UpdatePickCode sets the "pick_code" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdatePickCode() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdatePickCode()
	})
}

// SetName sets the "name" field.
func (u *SubtitleUpsertOne) SetName(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateName() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateName()
	})
}

// SetLanguage sets the "language" field.
func (u *SubtitleUpsertOne) SetLanguage(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateLanguage() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateLanguage()
	})
}

// SetFormat sets the "format" field.
func (u *SubtitleUpsertOne) SetFormat(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetFormat(v)
	})
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateFormat() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateFormat()
	})
}

// SetVersionTag sets the "version_tag" field.
func (u *SubtitleUpsertOne) SetVersionTag(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetVersionTag(v)
	})
}

// UpdateVersionTag sets the "version_tag" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateVersionTag() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateVersionTag()
	})
}

// SetSource sets the "source" field.
func (u *SubtitleUpsertOne) SetSource(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateSource() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateSource()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *SubtitleUpsertOne) SetSourceURL(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateSourceURL() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateSourceURL()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *SubtitleUpsertOne) SetStoragePath(v string) *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *SubtitleUpsertOne) UpdateStoragePath() *SubtitleUpsertOne {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateStoragePath()
	})
}

// Exec executes the query.
func (u *SubtitleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubtitleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubtitleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubtitleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubtitleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubtitleCreateBulk is the builder for creating many Subtitle entities in bulk.
type SubtitleCreateBulk struct {
	config
	err      error
	builders []*SubtitleCreate
	conflict []sql.ConflictOption
}

// Save creates the Subtitle entities in the database.
func (_c *SubtitleCreateBulk) Save(ctx context.Context) ([]*Subtitle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Subtitle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubtitleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubtitleCreateBulk) SaveX(ctx context.Context) []*Subtitle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubtitleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubtitleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Subtitle.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubtitleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubtitleCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubtitleUpsertBulk {
	_c.conflict = opts
	return &SubtitleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Subtitle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubtitleCreateBulk) OnConflictColumns(columns ...string) *SubtitleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubtitleUpsertBulk{
		create: _c,
	}
}

// SubtitleUpsertBulk is the builder for "upsert"-ing
// a bulk of Subtitle nodes.
type SubtitleUpsertBulk struct {
	create *SubtitleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Subtitle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubtitleUpsertBulk) UpdateNewValues() *SubtitleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subtitle.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Subtitle.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubtitleUpsertBulk) Ignore() *SubtitleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubtitleUpsertBulk) DoNothing() *SubtitleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubtitleCreateBulk.OnConflict
// documentation for more info.
func (u *SubtitleUpsertBulk) Update(set func(*SubtitleUpsert)) *SubtitleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubtitleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubtitleUpsertBulk) SetUpdatedAt(v time.Time) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateUpdatedAt() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMovieID sets the "movie_id" field.
func (u *SubtitleUpsertBulk) SetMovieID(v int) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetMovieID(v)
	})
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateMovieID() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateMovieID()
	})
}

// SetFileID sets the "file_id" field.
func (u *SubtitleUpsertBulk) SetFileID(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateFileID() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateFileID()
	})
}

// SetPickCode sets the "pick_code" field.
func (u *SubtitleUpsertBulk) SetPickCode(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetPickCode(v)
	})
}

// UpdatePickCode sets the "pick_code" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdatePickCode() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdatePickCode()
	})
}

// SetName sets the "name" field.
func (u *SubtitleUpsertBulk) SetName(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateName() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateName()
	})
}

// SetLanguage sets the "language" field.
func (u *SubtitleUpsertBulk) SetLanguage(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateLanguage() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateLanguage()
	})
}

// SetFormat sets the "format" field.
func (u *SubtitleUpsertBulk) SetFormat(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetFormat(v)
	})
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateFormat() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateFormat()
	})
}

// SetVersionTag sets the "version_tag" field.
func (u *SubtitleUpsertBulk) SetVersionTag(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetVersionTag(v)
	})
}

// UpdateVersionTag sets the "version_tag" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateVersionTag() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateVersionTag()
	})
}

// SetSource sets the "source" field.
func (u *SubtitleUpsertBulk) SetSource(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateSource() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateSource()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *SubtitleUpsertBulk) SetSourceURL(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateSourceURL() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateSourceURL()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *SubtitleUpsertBulk) SetStoragePath(v string) *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *SubtitleUpsertBulk) UpdateStoragePath() *SubtitleUpsertBulk {
	return u.Update(func(s *SubtitleUpsert) {
		s.UpdateStoragePath()
	})
}

// Exec executes the query.
func (u *SubtitleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubtitleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubtitleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubtitleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
