// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/predicate"
	"github.com/ppxb/miyabi/internal/ent/subtitle"
)

// SubtitleUpdate is the builder for updating Subtitle entities.
type SubtitleUpdate struct {
	config
	hooks    []Hook
	mutation *SubtitleMutation
}

// Where appends a list predicates to the SubtitleUpdate builder.
func (_u *SubtitleUpdate) Where(ps ...predicate.Subtitle) *SubtitleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubtitleUpdate) SetUpdatedAt(v time.Time) *SubtitleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *SubtitleUpdate) SetMovieID(v int) *SubtitleUpdate {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableMovieID(v *int) *SubtitleUpdate {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *SubtitleUpdate) SetFileID(v string) *SubtitleUpdate {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableFileID(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// SetPickCode sets the "pick_code" field.
func (_u *SubtitleUpdate) SetPickCode(v string) *SubtitleUpdate {
	_u.mutation.SetPickCode(v)
	return _u
}

// SetNillablePickCode sets the "pick_code" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillablePickCode(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetPickCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SubtitleUpdate) SetName(v string) *SubtitleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableName(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *SubtitleUpdate) SetLanguage(v string) *SubtitleUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableLanguage(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetFormat sets the "format" field.
func (_u *SubtitleUpdate) SetFormat(v string) *SubtitleUpdate {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableFormat(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetVersionTag sets the "version_tag" field.
func (_u *SubtitleUpdate) SetVersionTag(v string) *SubtitleUpdate {
	_u.mutation.SetVersionTag(v)
	return _u
}

// SetNillableVersionTag sets the "version_tag" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableVersionTag(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetVersionTag(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SubtitleUpdate) SetSource(v string) *SubtitleUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableSource(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *SubtitleUpdate) SetSourceURL(v string) *SubtitleUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableSourceURL(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *SubtitleUpdate) SetStoragePath(v string) *SubtitleUpdate {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *SubtitleUpdate) SetNillableStoragePath(v *string) *SubtitleUpdate {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *SubtitleUpdate) SetMovie(v *Movie) *SubtitleUpdate {
	return _u.SetMovieID(v.ID)
}

// Mutation returns the SubtitleMutation object of the builder.
func (_u *SubtitleUpdate) Mutation() *SubtitleMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *SubtitleUpdate) ClearMovie() *SubtitleUpdate {
	_u.mutation.ClearMovie()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubtitleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubtitleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubtitleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubtitleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubtitleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subtitle.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubtitleUpdate) check() error {
	if v, ok := _u.mutation.MovieID(); ok {
		if err := subtitle.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "Subtitle.movie_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := subtitle.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Subtitle.name": %w`, err)}
		}
	}
	if _u.mutation.MovieCleared() && len(_u.mutation.MovieIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subtitle.movie"`)
	}
	return nil
}

func (_u *SubtitleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subtitle.Table, subtitle.Columns, sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subtitle.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(subtitle.FieldFileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PickCode(); ok {
		_spec.SetField(subtitle.FieldPickCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subtitle.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(subtitle.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(subtitle.FieldFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.VersionTag(); ok {
		_spec.SetField(subtitle.FieldVersionTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(subtitle.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(subtitle.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(subtitle.FieldStoragePath, field.TypeString, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MovieTable,
			Columns: []string{subtitle.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MovieTable,
			Columns: []string{subtitle.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subtitle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubtitleUpdateOne is the builder for updating a single Subtitle entity.
type SubtitleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubtitleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubtitleUpdateOne) SetUpdatedAt(v time.Time) *SubtitleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *SubtitleUpdateOne) SetMovieID(v int) *SubtitleUpdateOne {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableMovieID(v *int) *SubtitleUpdateOne {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *SubtitleUpdateOne) SetFileID(v string) *SubtitleUpdateOne {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableFileID(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// SetPickCode sets the "pick_code" field.
func (_u *SubtitleUpdateOne) SetPickCode(v string) *SubtitleUpdateOne {
	_u.mutation.SetPickCode(v)
	return _u
}

// SetNillablePickCode sets the "pick_code" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillablePickCode(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetPickCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SubtitleUpdateOne) SetName(v string) *SubtitleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableName(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *SubtitleUpdateOne) SetLanguage(v string) *SubtitleUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableLanguage(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetFormat sets the "format" field.
func (_u *SubtitleUpdateOne) SetFormat(v string) *SubtitleUpdateOne {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableFormat(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetVersionTag sets the "version_tag" field.
func (_u *SubtitleUpdateOne) SetVersionTag(v string) *SubtitleUpdateOne {
	_u.mutation.SetVersionTag(v)
	return _u
}

// SetNillableVersionTag sets the "version_tag" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableVersionTag(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetVersionTag(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SubtitleUpdateOne) SetSource(v string) *SubtitleUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableSource(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *SubtitleUpdateOne) SetSourceURL(v string) *SubtitleUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableSourceURL(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *SubtitleUpdateOne) SetStoragePath(v string) *SubtitleUpdateOne {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *SubtitleUpdateOne) SetNillableStoragePath(v *string) *SubtitleUpdateOne {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *SubtitleUpdateOne) SetMovie(v *Movie) *SubtitleUpdateOne {
	return _u.SetMovieID(v.ID)
}

// Mutation returns the SubtitleMutation object of the builder.
func (_u *SubtitleUpdateOne) Mutation() *SubtitleMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *SubtitleUpdateOne) ClearMovie() *SubtitleUpdateOne {
	_u.mutation.ClearMovie()
	return _u
}

// Where appends a list predicates to the SubtitleUpdate builder.
func (_u *SubtitleUpdateOne) Where(ps ...predicate.Subtitle) *SubtitleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubtitleUpdateOne) Select(field string, fields ...string) *SubtitleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subtitle entity.
func (_u *SubtitleUpdateOne) Save(ctx context.Context) (*Subtitle, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubtitleUpdateOne) SaveX(ctx context.Context) *Subtitle {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubtitleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubtitleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubtitleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subtitle.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubtitleUpdateOne) check() error {
	if v, ok := _u.mutation.MovieID(); ok {
		if err := subtitle.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "Subtitle.movie_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := subtitle.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Subtitle.name": %w`, err)}
		}
	}
	if _u.mutation.MovieCleared() && len(_u.mutation.MovieIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subtitle.movie"`)
	}
	return nil
}

func (_u *SubtitleUpdateOne) sqlSave(ctx context.Context) (_node *Subtitle, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subtitle.Table, subtitle.Columns, sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subtitle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subtitle.FieldID)
		for _, f := range fields {
			if !subtitle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subtitle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subtitle.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(subtitle.FieldFileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PickCode(); ok {
		_spec.SetField(subtitle.FieldPickCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subtitle.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(subtitle.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(subtitle.FieldFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.VersionTag(); ok {
		_spec.SetField(subtitle.FieldVersionTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(subtitle.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(subtitle.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(subtitle.FieldStoragePath, field.TypeString, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MovieTable,
			Columns: []string{subtitle.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtitle.MovieTable,
			Columns: []string{subtitle.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subtitle{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subtitle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
