// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/subtitle"
)

// Subtitle is the model entity for the Subtitle schema.
type Subtitle struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// MovieID holds the value of the "movie_id" field.
	MovieID int `json:"movie_id,omitempty"`
	// FileID holds the value of the "file_id" field.
	FileID string `json:"file_id,omitempty"`
	// PickCode holds the value of the "pick_code" field.
	PickCode string `json:"pick_code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// Format holds the value of the "format" field.
	Format string `json:"format,omitempty"`
	// VersionTag holds the value of the "version_tag" field.
	VersionTag string `json:"version_tag,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SourceURL holds the value of the "source_url" field.
	SourceURL string `json:"source_url,omitempty"`
	// StoragePath holds the value of the "storage_path" field.
	StoragePath string `json:"storage_path,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubtitleQuery when eager-loading is set.
	Edges        SubtitleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubtitleEdges holds the relations/edges for other nodes in the graph.
type SubtitleEdges struct {
	// Movie holds the value of the movie edge.
	Movie *Movie `json:"movie,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MovieOrErr returns the Movie value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubtitleEdges) MovieOrErr() (*Movie, error) {
	if e.Movie != nil {
		return e.Movie, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: movie.Label}
	}
	return nil, &NotLoadedError{edge: "movie"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subtitle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subtitle.FieldID, subtitle.FieldMovieID:
			values[i] = new(sql.NullInt64)
		case subtitle.FieldFileID, subtitle.FieldPickCode, subtitle.FieldName, subtitle.FieldLanguage, subtitle.FieldFormat, subtitle.FieldVersionTag, subtitle.FieldSource, subtitle.FieldSourceURL, subtitle.FieldStoragePath:
			values[i] = new(sql.NullString)
		case subtitle.FieldCreatedAt, subtitle.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subtitle fields.
func (_m *Subtitle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subtitle.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case subtitle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subtitle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subtitle.FieldMovieID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field movie_id", values[i])
			} else if value.Valid {
				_m.MovieID = int(value.Int64)
			}
		case subtitle.FieldFileID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_id", values[i])
			} else if value.Valid {
				_m.FileID = value.String
			}
		case subtitle.FieldPickCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pick_code", values[i])
			} else if value.Valid {
				_m.PickCode = value.String
			}
		case subtitle.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case subtitle.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case subtitle.FieldFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field format", values[i])
			} else if value.Valid {
				_m.Format = value.String
			}
		case subtitle.FieldVersionTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version_tag", values[i])
			} else if value.Valid {
				_m.VersionTag = value.String
			}
		case subtitle.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case subtitle.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case subtitle.FieldStoragePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_path", values[i])
			} else if value.Valid {
				_m.StoragePath = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Subtitle.
// This includes values selected through modifiers, order, etc.
func (_m *Subtitle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMovie queries the "movie" edge of the Subtitle entity.
func (_m *Subtitle) QueryMovie() *MovieQuery {
	return NewSubtitleClient(_m.config).QueryMovie(_m)
}

// Update returns a builder for updating this Subtitle.
// Note that you need to call Subtitle.Unwrap() before calling this method if this Subtitle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Subtitle) Update() *SubtitleUpdateOne {
	return NewSubtitleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Subtitle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Subtitle) Unwrap() *Subtitle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subtitle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Subtitle) String() string {
	var builder strings.Builder
	builder.WriteString("Subtitle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("movie_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MovieID))
	builder.WriteString(", ")
	builder.WriteString("file_id=")
	builder.WriteString(_m.FileID)
	builder.WriteString(", ")
	builder.WriteString("pick_code=")
	builder.WriteString(_m.PickCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("format=")
	builder.WriteString(_m.Format)
	builder.WriteString(", ")
	builder.WriteString("version_tag=")
	builder.WriteString(_m.VersionTag)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("source_url=")
	builder.WriteString(_m.SourceURL)
	builder.WriteString(", ")
	builder.WriteString("storage_path=")
	builder.WriteString(_m.StoragePath)
	builder.WriteByte(')')
	return builder.String()
}

// Subtitles is a parsable slice of Subtitle.
type Subtitles []*Subtitle
