// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/predicate"
	"github.com/ppxb/miyabi/internal/ent/watchhistory"
)

// WatchHistoryUpdate is the builder for updating WatchHistory entities.
type WatchHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *WatchHistoryMutation
}

// Where appends a list predicates to the WatchHistoryUpdate builder.
func (_u *WatchHistoryUpdate) Where(ps ...predicate.WatchHistory) *WatchHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *WatchHistoryUpdate) SetAccountID(v string) *WatchHistoryUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillableAccountID(v *string) *WatchHistoryUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetRootID sets the "root_id" field.
func (_u *WatchHistoryUpdate) SetRootID(v string) *WatchHistoryUpdate {
	_u.mutation.SetRootID(v)
	return _u
}

// SetNillableRootID sets the "root_id" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillableRootID(v *string) *WatchHistoryUpdate {
	if v != nil {
		_u.SetRootID(*v)
	}
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *WatchHistoryUpdate) SetMovieID(v int) *WatchHistoryUpdate {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillableMovieID(v *int) *WatchHistoryUpdate {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// SetWatchedAt sets the "watched_at" field.
func (_u *WatchHistoryUpdate) SetWatchedAt(v time.Time) *WatchHistoryUpdate {
	_u.mutation.SetWatchedAt(v)
	return _u
}

// SetNillableWatchedAt sets the "watched_at" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillableWatchedAt(v *time.Time) *WatchHistoryUpdate {
	if v != nil {
		_u.SetWatchedAt(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *WatchHistoryUpdate) SetSessionID(v string) *WatchHistoryUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillableSessionID(v *string) *WatchHistoryUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *WatchHistoryUpdate) SetFileID(v string) *WatchHistoryUpdate {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillableFileID(v *string) *WatchHistoryUpdate {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *WatchHistoryUpdate) SetPosition(v float64) *WatchHistoryUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillablePosition(v *float64) *WatchHistoryUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *WatchHistoryUpdate) AddPosition(v float64) *WatchHistoryUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetDuration sets the "duration" field.
func (_u *WatchHistoryUpdate) SetDuration(v float64) *WatchHistoryUpdate {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillableDuration(v *float64) *WatchHistoryUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *WatchHistoryUpdate) AddDuration(v float64) *WatchHistoryUpdate {
	_u.mutation.AddDuration(v)
	return _u
}

// SetProgressVersion sets the "progress_version" field.
func (_u *WatchHistoryUpdate) SetProgressVersion(v int) *WatchHistoryUpdate {
	_u.mutation.ResetProgressVersion()
	_u.mutation.SetProgressVersion(v)
	return _u
}

// SetNillableProgressVersion sets the "progress_version" field if the given value is not nil.
func (_u *WatchHistoryUpdate) SetNillableProgressVersion(v *int) *WatchHistoryUpdate {
	if v != nil {
		_u.SetProgressVersion(*v)
	}
	return _u
}

// AddProgressVersion adds value to the "progress_version" field.
func (_u *WatchHistoryUpdate) AddProgressVersion(v int) *WatchHistoryUpdate {
	_u.mutation.AddProgressVersion(v)
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *WatchHistoryUpdate) SetMovie(v *Movie) *WatchHistoryUpdate {
	return _u.SetMovieID(v.ID)
}

// Mutation returns the WatchHistoryMutation object of the builder.
func (_u *WatchHistoryUpdate) Mutation() *WatchHistoryMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *WatchHistoryUpdate) ClearMovie() *WatchHistoryUpdate {
	_u.mutation.ClearMovie()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WatchHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WatchHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WatchHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WatchHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WatchHistoryUpdate) check() error {
	if v, ok := _u.mutation.AccountID(); ok {
		if err := watchhistory.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RootID(); ok {
		if err := watchhistory.RootIDValidator(v); err != nil {
			return &ValidationError{Name: "root_id", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.root_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MovieID(); ok {
		if err := watchhistory.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.movie_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := watchhistory.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProgressVersion(); ok {
		if err := watchhistory.ProgressVersionValidator(v); err != nil {
			return &ValidationError{Name: "progress_version", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.progress_version": %w`, err)}
		}
	}
	if _u.mutation.MovieCleared() && len(_u.mutation.MovieIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WatchHistory.movie"`)
	}
	return nil
}

func (_u *WatchHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(watchhistory.Table, watchhistory.Columns, sqlgraph.NewFieldSpec(watchhistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(watchhistory.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootID(); ok {
		_spec.SetField(watchhistory.FieldRootID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WatchedAt(); ok {
		_spec.SetField(watchhistory.FieldWatchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(watchhistory.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(watchhistory.FieldFileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(watchhistory.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(watchhistory.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(watchhistory.FieldDuration, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(watchhistory.FieldDuration, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ProgressVersion(); ok {
		_spec.SetField(watchhistory.FieldProgressVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgressVersion(); ok {
		_spec.AddField(watchhistory.FieldProgressVersion, field.TypeInt, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   watchhistory.MovieTable,
			Columns: []string{watchhistory.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   watchhistory.MovieTable,
			Columns: []string{watchhistory.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{watchhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WatchHistoryUpdateOne is the builder for updating a single WatchHistory entity.
type WatchHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WatchHistoryMutation
}

// SetAccountID sets the "account_id" field.
func (_u *WatchHistoryUpdateOne) SetAccountID(v string) *WatchHistoryUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillableAccountID(v *string) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetRootID sets the "root_id" field.
func (_u *WatchHistoryUpdateOne) SetRootID(v string) *WatchHistoryUpdateOne {
	_u.mutation.SetRootID(v)
	return _u
}

// SetNillableRootID sets the "root_id" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillableRootID(v *string) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetRootID(*v)
	}
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *WatchHistoryUpdateOne) SetMovieID(v int) *WatchHistoryUpdateOne {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillableMovieID(v *int) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// SetWatchedAt sets the "watched_at" field.
func (_u *WatchHistoryUpdateOne) SetWatchedAt(v time.Time) *WatchHistoryUpdateOne {
	_u.mutation.SetWatchedAt(v)
	return _u
}

// SetNillableWatchedAt sets the "watched_at" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillableWatchedAt(v *time.Time) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetWatchedAt(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *WatchHistoryUpdateOne) SetSessionID(v string) *WatchHistoryUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillableSessionID(v *string) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *WatchHistoryUpdateOne) SetFileID(v string) *WatchHistoryUpdateOne {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillableFileID(v *string) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *WatchHistoryUpdateOne) SetPosition(v float64) *WatchHistoryUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillablePosition(v *float64) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *WatchHistoryUpdateOne) AddPosition(v float64) *WatchHistoryUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetDuration sets the "duration" field.
func (_u *WatchHistoryUpdateOne) SetDuration(v float64) *WatchHistoryUpdateOne {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillableDuration(v *float64) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *WatchHistoryUpdateOne) AddDuration(v float64) *WatchHistoryUpdateOne {
	_u.mutation.AddDuration(v)
	return _u
}

// SetProgressVersion sets the "progress_version" field.
func (_u *WatchHistoryUpdateOne) SetProgressVersion(v int) *WatchHistoryUpdateOne {
	_u.mutation.ResetProgressVersion()
	_u.mutation.SetProgressVersion(v)
	return _u
}

// SetNillableProgressVersion sets the "progress_version" field if the given value is not nil.
func (_u *WatchHistoryUpdateOne) SetNillableProgressVersion(v *int) *WatchHistoryUpdateOne {
	if v != nil {
		_u.SetProgressVersion(*v)
	}
	return _u
}

// AddProgressVersion adds value to the "progress_version" field.
func (_u *WatchHistoryUpdateOne) AddProgressVersion(v int) *WatchHistoryUpdateOne {
	_u.mutation.AddProgressVersion(v)
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *WatchHistoryUpdateOne) SetMovie(v *Movie) *WatchHistoryUpdateOne {
	return _u.SetMovieID(v.ID)
}

// Mutation returns the WatchHistoryMutation object of the builder.
func (_u *WatchHistoryUpdateOne) Mutation() *WatchHistoryMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *WatchHistoryUpdateOne) ClearMovie() *WatchHistoryUpdateOne {
	_u.mutation.ClearMovie()
	return _u
}

// Where appends a list predicates to the WatchHistoryUpdate builder.
func (_u *WatchHistoryUpdateOne) Where(ps ...predicate.WatchHistory) *WatchHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WatchHistoryUpdateOne) Select(field string, fields ...string) *WatchHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WatchHistory entity.
func (_u *WatchHistoryUpdateOne) Save(ctx context.Context) (*WatchHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WatchHistoryUpdateOne) SaveX(ctx context.Context) *WatchHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WatchHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WatchHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WatchHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.AccountID(); ok {
		if err := watchhistory.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RootID(); ok {
		if err := watchhistory.RootIDValidator(v); err != nil {
			return &ValidationError{Name: "root_id", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.root_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MovieID(); ok {
		if err := watchhistory.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.movie_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := watchhistory.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProgressVersion(); ok {
		if err := watchhistory.ProgressVersionValidator(v); err != nil {
			return &ValidationError{Name: "progress_version", err: fmt.Errorf(`ent: validator failed for field "WatchHistory.progress_version": %w`, err)}
		}
	}
	if _u.mutation.MovieCleared() && len(_u.mutation.MovieIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WatchHistory.movie"`)
	}
	return nil
}

func (_u *WatchHistoryUpdateOne) sqlSave(ctx context.Context) (_node *WatchHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(watchhistory.Table, watchhistory.Columns, sqlgraph.NewFieldSpec(watchhistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WatchHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, watchhistory.FieldID)
		for _, f := range fields {
			if !watchhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != watchhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(watchhistory.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootID(); ok {
		_spec.SetField(watchhistory.FieldRootID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WatchedAt(); ok {
		_spec.SetField(watchhistory.FieldWatchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(watchhistory.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(watchhistory.FieldFileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(watchhistory.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(watchhistory.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(watchhistory.FieldDuration, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(watchhistory.FieldDuration, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ProgressVersion(); ok {
		_spec.SetField(watchhistory.FieldProgressVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgressVersion(); ok {
		_spec.AddField(watchhistory.FieldProgressVersion, field.TypeInt, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   watchhistory.MovieTable,
			Columns: []string{watchhistory.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   watchhistory.MovieTable,
			Columns: []string{watchhistory.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WatchHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{watchhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
