// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Actor is the predicate function for actor builders.
type Actor func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// WatchHistory is the predicate function for watchhistory builders.
type WatchHistory func(*sql.Selector)
