// Code generated by ent, DO NOT EDIT.

package subtitle

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldUpdatedAt, v))
}

// MovieID applies equality check predicate on the "movie_id" field. It's identical to MovieIDEQ.
func MovieID(v int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldMovieID, v))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldFileID, v))
}

// PickCode applies equality check predicate on the "pick_code" field. It's identical to PickCodeEQ.
func PickCode(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldPickCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldName, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldLanguage, v))
}

// Format applies equality check predicate on the "format" field. It's identical to FormatEQ.
func Format(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldFormat, v))
}

// VersionTag applies equality check predicate on the "version_tag" field. It's identical to VersionTagEQ.
func VersionTag(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldVersionTag, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldSource, v))
}

// SourceURL applies equality check predicate on the "source_url" field. It's identical to SourceURLEQ.
func SourceURL(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldSourceURL, v))
}

// StoragePath applies equality check predicate on the "storage_path" field. It's identical to StoragePathEQ.
func StoragePath(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldStoragePath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldUpdatedAt, v))
}

// MovieIDEQ applies the EQ predicate on the "movie_id" field.
func MovieIDEQ(v int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldMovieID, v))
}

// MovieIDNEQ applies the NEQ predicate on the "movie_id" field.
func MovieIDNEQ(v int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldMovieID, v))
}

// MovieIDIn applies the In predicate on the "movie_id" field.
func MovieIDIn(vs ...int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldMovieID, vs...))
}

// MovieIDNotIn applies the NotIn predicate on the "movie_id" field.
func MovieIDNotIn(vs ...int) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldMovieID, vs...))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldFileID, vs...))
}

// FileIDGT applies the GT predicate on the "file_id" field.
func FileIDGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldFileID, v))
}

// FileIDGTE applies the GTE predicate on the "file_id" field.
func FileIDGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldFileID, v))
}

// FileIDLT applies the LT predicate on the "file_id" field.
func FileIDLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldFileID, v))
}

// FileIDLTE applies the LTE predicate on the "file_id" field.
func FileIDLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldFileID, v))
}

// FileIDContains applies the Contains predicate on the "file_id" field.
func FileIDContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldFileID, v))
}

// FileIDHasPrefix applies the HasPrefix predicate on the "file_id" field.
func FileIDHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldFileID, v))
}

// FileIDHasSuffix applies the HasSuffix predicate on the "file_id" field.
func FileIDHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldFileID, v))
}

// FileIDEqualFold applies the EqualFold predicate on the "file_id" field.
func FileIDEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldFileID, v))
}

// FileIDContainsFold applies the ContainsFold predicate on the "file_id" field.
func FileIDContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldFileID, v))
}

// PickCodeEQ applies the EQ predicate on the "pick_code" field.
func PickCodeEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldPickCode, v))
}

// PickCodeNEQ applies the NEQ predicate on the "pick_code" field.
func PickCodeNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldPickCode, v))
}

// PickCodeIn applies the In predicate on the "pick_code" field.
func PickCodeIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldPickCode, vs...))
}

// PickCodeNotIn applies the NotIn predicate on the "pick_code" field.
func PickCodeNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldPickCode, vs...))
}

// PickCodeGT applies the GT predicate on the "pick_code" field.
func PickCodeGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldPickCode, v))
}

// PickCodeGTE applies the GTE predicate on the "pick_code" field.
func PickCodeGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldPickCode, v))
}

// PickCodeLT applies the LT predicate on the "pick_code" field.
func PickCodeLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldPickCode, v))
}

// PickCodeLTE applies the LTE predicate on the "pick_code" field.
func PickCodeLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldPickCode, v))
}

// PickCodeContains applies the Contains predicate on the "pick_code" field.
func PickCodeContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldPickCode, v))
}

// PickCodeHasPrefix applies the HasPrefix predicate on the "pick_code" field.
func PickCodeHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldPickCode, v))
}

// PickCodeHasSuffix applies the HasSuffix predicate on the "pick_code" field.
func PickCodeHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldPickCode, v))
}

// PickCodeEqualFold applies the EqualFold predicate on the "pick_code" field.
func PickCodeEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldPickCode, v))
}

// PickCodeContainsFold applies the ContainsFold predicate on the "pick_code" field.
func PickCodeContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldPickCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldName, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldLanguage, v))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldFormat, vs...))
}

// FormatGT applies the GT predicate on the "format" field.
func FormatGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldFormat, v))
}

// FormatGTE applies the GTE predicate on the "format" field.
func FormatGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldFormat, v))
}

// FormatLT applies the LT predicate on the "format" field.
func FormatLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldFormat, v))
}

// FormatLTE applies the LTE predicate on the "format" field.
func FormatLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldFormat, v))
}

// FormatContains applies the Contains predicate on the "format" field.
func FormatContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldFormat, v))
}

// FormatHasPrefix applies the HasPrefix predicate on the "format" field.
func FormatHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldFormat, v))
}

// FormatHasSuffix applies the HasSuffix predicate on the "format" field.
func FormatHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldFormat, v))
}

// FormatEqualFold applies the EqualFold predicate on the "format" field.
func FormatEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldFormat, v))
}

// FormatContainsFold applies the ContainsFold predicate on the "format" field.
func FormatContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldFormat, v))
}

// VersionTagEQ applies the EQ predicate on the "version_tag" field.
func VersionTagEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldVersionTag, v))
}

// VersionTagNEQ applies the NEQ predicate on the "version_tag" field.
func VersionTagNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldVersionTag, v))
}

// VersionTagIn applies the In predicate on the "version_tag" field.
func VersionTagIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldVersionTag, vs...))
}

// VersionTagNotIn applies the NotIn predicate on the "version_tag" field.
func VersionTagNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldVersionTag, vs...))
}

// VersionTagGT applies the GT predicate on the "version_tag" field.
func VersionTagGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldVersionTag, v))
}

// VersionTagGTE applies the GTE predicate on the "version_tag" field.
func VersionTagGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldVersionTag, v))
}

// VersionTagLT applies the LT predicate on the "version_tag" field.
func VersionTagLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldVersionTag, v))
}

// VersionTagLTE applies the LTE predicate on the "version_tag" field.
func VersionTagLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldVersionTag, v))
}

// VersionTagContains applies the Contains predicate on the "version_tag" field.
func VersionTagContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldVersionTag, v))
}

// VersionTagHasPrefix applies the HasPrefix predicate on the "version_tag" field.
func VersionTagHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldVersionTag, v))
}

// VersionTagHasSuffix applies the HasSuffix predicate on the "version_tag" field.
func VersionTagHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldVersionTag, v))
}

// VersionTagEqualFold applies the EqualFold predicate on the "version_tag" field.
func VersionTagEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldVersionTag, v))
}

// VersionTagContainsFold applies the ContainsFold predicate on the "version_tag" field.
func VersionTagContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldVersionTag, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldSource, v))
}

// SourceURLEQ applies the EQ predicate on the "source_url" field.
func SourceURLEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldSourceURL, v))
}

// SourceURLNEQ applies the NEQ predicate on the "source_url" field.
func SourceURLNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldSourceURL, v))
}

// SourceURLIn applies the In predicate on the "source_url" field.
func SourceURLIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldSourceURL, vs...))
}

// SourceURLNotIn applies the NotIn predicate on the "source_url" field.
func SourceURLNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldSourceURL, vs...))
}

// SourceURLGT applies the GT predicate on the "source_url" field.
func SourceURLGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldSourceURL, v))
}

// SourceURLGTE applies the GTE predicate on the "source_url" field.
func SourceURLGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldSourceURL, v))
}

// SourceURLLT applies the LT predicate on the "source_url" field.
func SourceURLLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldSourceURL, v))
}

// SourceURLLTE applies the LTE predicate on the "source_url" field.
func SourceURLLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldSourceURL, v))
}

// SourceURLContains applies the Contains predicate on the "source_url" field.
func SourceURLContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldSourceURL, v))
}

// SourceURLHasPrefix applies the HasPrefix predicate on the "source_url" field.
func SourceURLHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldSourceURL, v))
}

// SourceURLHasSuffix applies the HasSuffix predicate on the "source_url" field.
func SourceURLHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldSourceURL, v))
}

// SourceURLEqualFold applies the EqualFold predicate on the "source_url" field.
func SourceURLEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldSourceURL, v))
}

// SourceURLContainsFold applies the ContainsFold predicate on the "source_url" field.
func SourceURLContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldSourceURL, v))
}

// StoragePathEQ applies the EQ predicate on the "storage_path" field.
func StoragePathEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEQ(FieldStoragePath, v))
}

// StoragePathNEQ applies the NEQ predicate on the "storage_path" field.
func StoragePathNEQ(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNEQ(FieldStoragePath, v))
}

// StoragePathIn applies the In predicate on the "storage_path" field.
func StoragePathIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldIn(FieldStoragePath, vs...))
}

// StoragePathNotIn applies the NotIn predicate on the "storage_path" field.
func StoragePathNotIn(vs ...string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldNotIn(FieldStoragePath, vs...))
}

// StoragePathGT applies the GT predicate on the "storage_path" field.
func StoragePathGT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGT(FieldStoragePath, v))
}

// StoragePathGTE applies the GTE predicate on the "storage_path" field.
func StoragePathGTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldGTE(FieldStoragePath, v))
}

// StoragePathLT applies the LT predicate on the "storage_path" field.
func StoragePathLT(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLT(FieldStoragePath, v))
}

// StoragePathLTE applies the LTE predicate on the "storage_path" field.
func StoragePathLTE(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldLTE(FieldStoragePath, v))
}

// StoragePathContains applies the Contains predicate on the "storage_path" field.
func StoragePathContains(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContains(FieldStoragePath, v))
}

// StoragePathHasPrefix applies the HasPrefix predicate on the "storage_path" field.
func StoragePathHasPrefix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasPrefix(FieldStoragePath, v))
}

// StoragePathHasSuffix applies the HasSuffix predicate on the "storage_path" field.
func StoragePathHasSuffix(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldHasSuffix(FieldStoragePath, v))
}

// StoragePathEqualFold applies the EqualFold predicate on the "storage_path" field.
func StoragePathEqualFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldEqualFold(FieldStoragePath, v))
}

// StoragePathContainsFold applies the ContainsFold predicate on the "storage_path" field.
func StoragePathContainsFold(v string) predicate.Subtitle {
	return predicate.Subtitle(sql.FieldContainsFold(FieldStoragePath, v))
}

// HasMovie applies the HasEdge predicate on the "movie" edge.
func HasMovie() predicate.Subtitle {
	return predicate.Subtitle(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MovieTable, MovieColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMovieWith applies the HasEdge predicate on the "movie" edge with a given conditions (other predicates).
func HasMovieWith(preds ...predicate.Movie) predicate.Subtitle {
	return predicate.Subtitle(func(s *sql.Selector) {
		step := newMovieStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subtitle) predicate.Subtitle {
	return predicate.Subtitle(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subtitle) predicate.Subtitle {
	return predicate.Subtitle(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subtitle) predicate.Subtitle {
	return predicate.Subtitle(sql.NotPredicates(p))
}
