// Code generated by ent, DO NOT EDIT.

package watchhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the watchhistory type in the database.
	Label = "watch_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldRootID holds the string denoting the root_id field in the database.
	FieldRootID = "root_id"
	// FieldMovieID holds the string denoting the movie_id field in the database.
	FieldMovieID = "movie_id"
	// FieldWatchedAt holds the string denoting the watched_at field in the database.
	FieldWatchedAt = "watched_at"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldFileID holds the string denoting the file_id field in the database.
	FieldFileID = "file_id"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldProgressVersion holds the string denoting the progress_version field in the database.
	FieldProgressVersion = "progress_version"
	// EdgeMovie holds the string denoting the movie edge name in mutations.
	EdgeMovie = "movie"
	// Table holds the table name of the watchhistory in the database.
	Table = "watch_histories"
	// MovieTable is the table that holds the movie relation/edge.
	MovieTable = "watch_histories"
	// MovieInverseTable is the table name for the Movie entity.
	// It exists in this package in order to avoid circular dependency with the "movie" package.
	MovieInverseTable = "movies"
	// MovieColumn is the table column denoting the movie relation/edge.
	MovieColumn = "movie_id"
)

// Columns holds all SQL columns for watchhistory fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldRootID,
	FieldMovieID,
	FieldWatchedAt,
	FieldSessionID,
	FieldFileID,
	FieldPosition,
	FieldDuration,
	FieldProgressVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	AccountIDValidator func(string) error
	// RootIDValidator is a validator for the "root_id" field. It is called by the builders before save.
	RootIDValidator func(string) error
	// MovieIDValidator is a validator for the "movie_id" field. It is called by the builders before save.
	MovieIDValidator func(int) error
	// DefaultWatchedAt holds the default value on creation for the "watched_at" field.
	DefaultWatchedAt func() time.Time
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// DefaultFileID holds the default value on creation for the "file_id" field.
	DefaultFileID string
	// DefaultPosition holds the default value on creation for the "position" field.
	DefaultPosition float64
	// DefaultDuration holds the default value on creation for the "duration" field.
	DefaultDuration float64
	// DefaultProgressVersion holds the default value on creation for the "progress_version" field.
	DefaultProgressVersion int
	// ProgressVersionValidator is a validator for the "progress_version" field. It is called by the builders before save.
	ProgressVersionValidator func(int) error
)

// OrderOption defines the ordering options for the WatchHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByRootID orders the results by the root_id field.
func ByRootID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRootID, opts...).ToFunc()
}

// ByMovieID orders the results by the movie_id field.
func ByMovieID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMovieID, opts...).ToFunc()
}

// ByWatchedAt orders the results by the watched_at field.
func ByWatchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWatchedAt, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByFileID orders the results by the file_id field.
func ByFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileID, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}

// ByProgressVersion orders the results by the progress_version field.
func ByProgressVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgressVersion, opts...).ToFunc()
}

// ByMovieField orders the results by movie field.
func ByMovieField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMovieStep(), sql.OrderByField(field, opts...))
	}
}
func newMovieStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MovieInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MovieTable, MovieColumn),
	)
}
