// Code generated by ent, DO NOT EDIT.

package watchhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldAccountID, v))
}

// RootID applies equality check predicate on the "root_id" field. It's identical to RootIDEQ.
func RootID(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldRootID, v))
}

// MovieID applies equality check predicate on the "movie_id" field. It's identical to MovieIDEQ.
func MovieID(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldMovieID, v))
}

// WatchedAt applies equality check predicate on the "watched_at" field. It's identical to WatchedAtEQ.
func WatchedAt(v time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldWatchedAt, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldSessionID, v))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldFileID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldPosition, v))
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldDuration, v))
}

// ProgressVersion applies equality check predicate on the "progress_version" field. It's identical to ProgressVersionEQ.
func ProgressVersion(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldProgressVersion, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldContainsFold(FieldAccountID, v))
}

// RootIDEQ applies the EQ predicate on the "root_id" field.
func RootIDEQ(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldRootID, v))
}

// RootIDNEQ applies the NEQ predicate on the "root_id" field.
func RootIDNEQ(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldRootID, v))
}

// RootIDIn applies the In predicate on the "root_id" field.
func RootIDIn(vs ...string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldRootID, vs...))
}

// RootIDNotIn applies the NotIn predicate on the "root_id" field.
func RootIDNotIn(vs ...string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldRootID, vs...))
}

// RootIDGT applies the GT predicate on the "root_id" field.
func RootIDGT(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldRootID, v))
}

// RootIDGTE applies the GTE predicate on the "root_id" field.
func RootIDGTE(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldRootID, v))
}

// RootIDLT applies the LT predicate on the "root_id" field.
func RootIDLT(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldRootID, v))
}

// RootIDLTE applies the LTE predicate on the "root_id" field.
func RootIDLTE(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldRootID, v))
}

// RootIDContains applies the Contains predicate on the "root_id" field.
func RootIDContains(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldContains(FieldRootID, v))
}

// RootIDHasPrefix applies the HasPrefix predicate on the "root_id" field.
func RootIDHasPrefix(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldHasPrefix(FieldRootID, v))
}

// RootIDHasSuffix applies the HasSuffix predicate on the "root_id" field.
func RootIDHasSuffix(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldHasSuffix(FieldRootID, v))
}

// RootIDEqualFold applies the EqualFold predicate on the "root_id" field.
func RootIDEqualFold(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEqualFold(FieldRootID, v))
}

// RootIDContainsFold applies the ContainsFold predicate on the "root_id" field.
func RootIDContainsFold(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldContainsFold(FieldRootID, v))
}

// MovieIDEQ applies the EQ predicate on the "movie_id" field.
func MovieIDEQ(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldMovieID, v))
}

// MovieIDNEQ applies the NEQ predicate on the "movie_id" field.
func MovieIDNEQ(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldMovieID, v))
}

// MovieIDIn applies the In predicate on the "movie_id" field.
func MovieIDIn(vs ...int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldMovieID, vs...))
}

// MovieIDNotIn applies the NotIn predicate on the "movie_id" field.
func MovieIDNotIn(vs ...int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldMovieID, vs...))
}

// WatchedAtEQ applies the EQ predicate on the "watched_at" field.
func WatchedAtEQ(v time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldWatchedAt, v))
}

// WatchedAtNEQ applies the NEQ predicate on the "watched_at" field.
func WatchedAtNEQ(v time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldWatchedAt, v))
}

// WatchedAtIn applies the In predicate on the "watched_at" field.
func WatchedAtIn(vs ...time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldWatchedAt, vs...))
}

// WatchedAtNotIn applies the NotIn predicate on the "watched_at" field.
func WatchedAtNotIn(vs ...time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldWatchedAt, vs...))
}

// WatchedAtGT applies the GT predicate on the "watched_at" field.
func WatchedAtGT(v time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldWatchedAt, v))
}

// WatchedAtGTE applies the GTE predicate on the "watched_at" field.
func WatchedAtGTE(v time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldWatchedAt, v))
}

// WatchedAtLT applies the LT predicate on the "watched_at" field.
func WatchedAtLT(v time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldWatchedAt, v))
}

// WatchedAtLTE applies the LTE predicate on the "watched_at" field.
func WatchedAtLTE(v time.Time) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldWatchedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldContainsFold(FieldSessionID, v))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldFileID, vs...))
}

// FileIDGT applies the GT predicate on the "file_id" field.
func FileIDGT(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldFileID, v))
}

// FileIDGTE applies the GTE predicate on the "file_id" field.
func FileIDGTE(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldFileID, v))
}

// FileIDLT applies the LT predicate on the "file_id" field.
func FileIDLT(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldFileID, v))
}

// FileIDLTE applies the LTE predicate on the "file_id" field.
func FileIDLTE(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldFileID, v))
}

// FileIDContains applies the Contains predicate on the "file_id" field.
func FileIDContains(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldContains(FieldFileID, v))
}

// FileIDHasPrefix applies the HasPrefix predicate on the "file_id" field.
func FileIDHasPrefix(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldHasPrefix(FieldFileID, v))
}

// FileIDHasSuffix applies the HasSuffix predicate on the "file_id" field.
func FileIDHasSuffix(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldHasSuffix(FieldFileID, v))
}

// FileIDEqualFold applies the EqualFold predicate on the "file_id" field.
func FileIDEqualFold(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEqualFold(FieldFileID, v))
}

// FileIDContainsFold applies the ContainsFold predicate on the "file_id" field.
func FileIDContainsFold(v string) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldContainsFold(FieldFileID, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldPosition, v))
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldDuration, v))
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldDuration, v))
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldDuration, vs...))
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldDuration, vs...))
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldDuration, v))
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldDuration, v))
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldDuration, v))
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v float64) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldDuration, v))
}

// ProgressVersionEQ applies the EQ predicate on the "progress_version" field.
func ProgressVersionEQ(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldEQ(FieldProgressVersion, v))
}

// ProgressVersionNEQ applies the NEQ predicate on the "progress_version" field.
func ProgressVersionNEQ(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNEQ(FieldProgressVersion, v))
}

// ProgressVersionIn applies the In predicate on the "progress_version" field.
func ProgressVersionIn(vs ...int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldIn(FieldProgressVersion, vs...))
}

// ProgressVersionNotIn applies the NotIn predicate on the "progress_version" field.
func ProgressVersionNotIn(vs ...int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldNotIn(FieldProgressVersion, vs...))
}

// ProgressVersionGT applies the GT predicate on the "progress_version" field.
func ProgressVersionGT(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGT(FieldProgressVersion, v))
}

// ProgressVersionGTE applies the GTE predicate on the "progress_version" field.
func ProgressVersionGTE(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldGTE(FieldProgressVersion, v))
}

// ProgressVersionLT applies the LT predicate on the "progress_version" field.
func ProgressVersionLT(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLT(FieldProgressVersion, v))
}

// ProgressVersionLTE applies the LTE predicate on the "progress_version" field.
func ProgressVersionLTE(v int) predicate.WatchHistory {
	return predicate.WatchHistory(sql.FieldLTE(FieldProgressVersion, v))
}

// HasMovie applies the HasEdge predicate on the "movie" edge.
func HasMovie() predicate.WatchHistory {
	return predicate.WatchHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MovieTable, MovieColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMovieWith applies the HasEdge predicate on the "movie" edge with a given conditions (other predicates).
func HasMovieWith(preds ...predicate.Movie) predicate.WatchHistory {
	return predicate.WatchHistory(func(s *sql.Selector) {
		step := newMovieStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WatchHistory) predicate.WatchHistory {
	return predicate.WatchHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WatchHistory) predicate.WatchHistory {
	return predicate.WatchHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WatchHistory) predicate.WatchHistory {
	return predicate.WatchHistory(sql.NotPredicates(p))
}
