// Code generated by ent, DO NOT EDIT.

package file

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.File {
	return predicate.File(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.File {
	return predicate.File(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.File {
	return predicate.File(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.File {
	return predicate.File(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.File {
	return predicate.File(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.File {
	return predicate.File(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.File {
	return predicate.File(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.File {
	return predicate.File(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.File {
	return predicate.File(sql.FieldEQ(FieldUpdatedAt, v))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldFileID, v))
}

// PickCode applies equality check predicate on the "pick_code" field. It's identical to PickCodeEQ.
func PickCode(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldPickCode, v))
}

// Sha1 applies equality check predicate on the "sha1" field. It's identical to Sha1EQ.
func Sha1(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldSha1, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldName, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.File {
	return predicate.File(sql.FieldEQ(FieldSize, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldParentID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldAccountID, v))
}

// RootID applies equality check predicate on the "root_id" field. It's identical to RootIDEQ.
func RootID(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldRootID, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldPath, v))
}

// ScanID applies equality check predicate on the "scan_id" field. It's identical to ScanIDEQ.
func ScanID(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldScanID, v))
}

// MovieID applies equality check predicate on the "movie_id" field. It's identical to MovieIDEQ.
func MovieID(v int) predicate.File {
	return predicate.File(sql.FieldEQ(FieldMovieID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.File {
	return predicate.File(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.File {
	return predicate.File(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.File {
	return predicate.File(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.File {
	return predicate.File(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.File {
	return predicate.File(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.File {
	return predicate.File(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.File {
	return predicate.File(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.File {
	return predicate.File(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.File {
	return predicate.File(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.File {
	return predicate.File(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.File {
	return predicate.File(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.File {
	return predicate.File(sql.FieldLTE(FieldUpdatedAt, v))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldFileID, vs...))
}

// FileIDGT applies the GT predicate on the "file_id" field.
func FileIDGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldFileID, v))
}

// FileIDGTE applies the GTE predicate on the "file_id" field.
func FileIDGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldFileID, v))
}

// FileIDLT applies the LT predicate on the "file_id" field.
func FileIDLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldFileID, v))
}

// FileIDLTE applies the LTE predicate on the "file_id" field.
func FileIDLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldFileID, v))
}

// FileIDContains applies the Contains predicate on the "file_id" field.
func FileIDContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldFileID, v))
}

// FileIDHasPrefix applies the HasPrefix predicate on the "file_id" field.
func FileIDHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldFileID, v))
}

// FileIDHasSuffix applies the HasSuffix predicate on the "file_id" field.
func FileIDHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldFileID, v))
}

// FileIDEqualFold applies the EqualFold predicate on the "file_id" field.
func FileIDEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldFileID, v))
}

// FileIDContainsFold applies the ContainsFold predicate on the "file_id" field.
func FileIDContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldFileID, v))
}

// PickCodeEQ applies the EQ predicate on the "pick_code" field.
func PickCodeEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldPickCode, v))
}

// PickCodeNEQ applies the NEQ predicate on the "pick_code" field.
func PickCodeNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldPickCode, v))
}

// PickCodeIn applies the In predicate on the "pick_code" field.
func PickCodeIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldPickCode, vs...))
}

// PickCodeNotIn applies the NotIn predicate on the "pick_code" field.
func PickCodeNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldPickCode, vs...))
}

// PickCodeGT applies the GT predicate on the "pick_code" field.
func PickCodeGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldPickCode, v))
}

// PickCodeGTE applies the GTE predicate on the "pick_code" field.
func PickCodeGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldPickCode, v))
}

// PickCodeLT applies the LT predicate on the "pick_code" field.
func PickCodeLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldPickCode, v))
}

// PickCodeLTE applies the LTE predicate on the "pick_code" field.
func PickCodeLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldPickCode, v))
}

// PickCodeContains applies the Contains predicate on the "pick_code" field.
func PickCodeContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldPickCode, v))
}

// PickCodeHasPrefix applies the HasPrefix predicate on the "pick_code" field.
func PickCodeHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldPickCode, v))
}

// PickCodeHasSuffix applies the HasSuffix predicate on the "pick_code" field.
func PickCodeHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldPickCode, v))
}

// PickCodeEqualFold applies the EqualFold predicate on the "pick_code" field.
func PickCodeEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldPickCode, v))
}

// PickCodeContainsFold applies the ContainsFold predicate on the "pick_code" field.
func PickCodeContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldPickCode, v))
}

// Sha1EQ applies the EQ predicate on the "sha1" field.
func Sha1EQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldSha1, v))
}

// Sha1NEQ applies the NEQ predicate on the "sha1" field.
func Sha1NEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldSha1, v))
}

// Sha1In applies the In predicate on the "sha1" field.
func Sha1In(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldSha1, vs...))
}

// Sha1NotIn applies the NotIn predicate on the "sha1" field.
func Sha1NotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldSha1, vs...))
}

// Sha1GT applies the GT predicate on the "sha1" field.
func Sha1GT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldSha1, v))
}

// Sha1GTE applies the GTE predicate on the "sha1" field.
func Sha1GTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldSha1, v))
}

// Sha1LT applies the LT predicate on the "sha1" field.
func Sha1LT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldSha1, v))
}

// Sha1LTE applies the LTE predicate on the "sha1" field.
func Sha1LTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldSha1, v))
}

// Sha1Contains applies the Contains predicate on the "sha1" field.
func Sha1Contains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldSha1, v))
}

// Sha1HasPrefix applies the HasPrefix predicate on the "sha1" field.
func Sha1HasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldSha1, v))
}

// Sha1HasSuffix applies the HasSuffix predicate on the "sha1" field.
func Sha1HasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldSha1, v))
}

// Sha1EqualFold applies the EqualFold predicate on the "sha1" field.
func Sha1EqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldSha1, v))
}

// Sha1ContainsFold applies the ContainsFold predicate on the "sha1" field.
func Sha1ContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldSha1, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldName, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.File {
	return predicate.File(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.File {
	return predicate.File(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.File {
	return predicate.File(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.File {
	return predicate.File(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.File {
	return predicate.File(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.File {
	return predicate.File(sql.FieldLTE(FieldSize, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldParentID, v))
}

// ParentIDContains applies the Contains predicate on the "parent_id" field.
func ParentIDContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldParentID, v))
}

// ParentIDHasPrefix applies the HasPrefix predicate on the "parent_id" field.
func ParentIDHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldParentID, v))
}

// ParentIDHasSuffix applies the HasSuffix predicate on the "parent_id" field.
func ParentIDHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldParentID, v))
}

// ParentIDEqualFold applies the EqualFold predicate on the "parent_id" field.
func ParentIDEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldParentID, v))
}

// ParentIDContainsFold applies the ContainsFold predicate on the "parent_id" field.
func ParentIDContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldParentID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldAccountID, v))
}

// RootIDEQ applies the EQ predicate on the "root_id" field.
func RootIDEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldRootID, v))
}

// RootIDNEQ applies the NEQ predicate on the "root_id" field.
func RootIDNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldRootID, v))
}

// RootIDIn applies the In predicate on the "root_id" field.
func RootIDIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldRootID, vs...))
}

// RootIDNotIn applies the NotIn predicate on the "root_id" field.
func RootIDNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldRootID, vs...))
}

// RootIDGT applies the GT predicate on the "root_id" field.
func RootIDGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldRootID, v))
}

// RootIDGTE applies the GTE predicate on the "root_id" field.
func RootIDGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldRootID, v))
}

// RootIDLT applies the LT predicate on the "root_id" field.
func RootIDLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldRootID, v))
}

// RootIDLTE applies the LTE predicate on the "root_id" field.
func RootIDLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldRootID, v))
}

// RootIDContains applies the Contains predicate on the "root_id" field.
func RootIDContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldRootID, v))
}

// RootIDHasPrefix applies the HasPrefix predicate on the "root_id" field.
func RootIDHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldRootID, v))
}

// RootIDHasSuffix applies the HasSuffix predicate on the "root_id" field.
func RootIDHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldRootID, v))
}

// RootIDEqualFold applies the EqualFold predicate on the "root_id" field.
func RootIDEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldRootID, v))
}

// RootIDContainsFold applies the ContainsFold predicate on the "root_id" field.
func RootIDContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldRootID, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldPath, v))
}

// ScanIDEQ applies the EQ predicate on the "scan_id" field.
func ScanIDEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldScanID, v))
}

// ScanIDNEQ applies the NEQ predicate on the "scan_id" field.
func ScanIDNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldScanID, v))
}

// ScanIDIn applies the In predicate on the "scan_id" field.
func ScanIDIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldScanID, vs...))
}

// ScanIDNotIn applies the NotIn predicate on the "scan_id" field.
func ScanIDNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldScanID, vs...))
}

// ScanIDGT applies the GT predicate on the "scan_id" field.
func ScanIDGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldScanID, v))
}

// ScanIDGTE applies the GTE predicate on the "scan_id" field.
func ScanIDGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldScanID, v))
}

// ScanIDLT applies the LT predicate on the "scan_id" field.
func ScanIDLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldScanID, v))
}

// ScanIDLTE applies the LTE predicate on the "scan_id" field.
func ScanIDLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldScanID, v))
}

// ScanIDContains applies the Contains predicate on the "scan_id" field.
func ScanIDContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldScanID, v))
}

// ScanIDHasPrefix applies the HasPrefix predicate on the "scan_id" field.
func ScanIDHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldScanID, v))
}

// ScanIDHasSuffix applies the HasSuffix predicate on the "scan_id" field.
func ScanIDHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldScanID, v))
}

// ScanIDEqualFold applies the EqualFold predicate on the "scan_id" field.
func ScanIDEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldScanID, v))
}

// ScanIDContainsFold applies the ContainsFold predicate on the "scan_id" field.
func ScanIDContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldScanID, v))
}

// MovieIDEQ applies the EQ predicate on the "movie_id" field.
func MovieIDEQ(v int) predicate.File {
	return predicate.File(sql.FieldEQ(FieldMovieID, v))
}

// MovieIDNEQ applies the NEQ predicate on the "movie_id" field.
func MovieIDNEQ(v int) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldMovieID, v))
}

// MovieIDIn applies the In predicate on the "movie_id" field.
func MovieIDIn(vs ...int) predicate.File {
	return predicate.File(sql.FieldIn(FieldMovieID, vs...))
}

// MovieIDNotIn applies the NotIn predicate on the "movie_id" field.
func MovieIDNotIn(vs ...int) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldMovieID, vs...))
}

// MovieIDIsNil applies the IsNil predicate on the "movie_id" field.
func MovieIDIsNil() predicate.File {
	return predicate.File(sql.FieldIsNull(FieldMovieID))
}

// MovieIDNotNil applies the NotNil predicate on the "movie_id" field.
func MovieIDNotNil() predicate.File {
	return predicate.File(sql.FieldNotNull(FieldMovieID))
}

// HasMovie applies the HasEdge predicate on the "movie" edge.
func HasMovie() predicate.File {
	return predicate.File(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MovieTable, MovieColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMovieWith applies the HasEdge predicate on the "movie" edge with a given conditions (other predicates).
func HasMovieWith(preds ...predicate.Movie) predicate.File {
	return predicate.File(func(s *sql.Selector) {
		step := newMovieStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.File) predicate.File {
	return predicate.File(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.File) predicate.File {
	return predicate.File(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.File) predicate.File {
	return predicate.File(sql.NotPredicates(p))
}
