// Code generated by ent, DO NOT EDIT.

package embynotification

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldUpdatedAt, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldPath, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldRevision, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldAttempts, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldNextAttemptAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLTE(FieldUpdatedAt, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldContainsFold(FieldPath, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLTE(FieldRevision, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLTE(FieldAttempts, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLTE(FieldNextAttemptAt, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.FieldContainsFold(FieldLastError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmbyNotification) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmbyNotification) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmbyNotification) predicate.EmbyNotification {
	return predicate.EmbyNotification(sql.NotPredicates(p))
}
